# -*- coding: utf-8 -*-
from build import dester
from content.shared import KENNIS_LINKS, ONTRUIM_LINKS, hulpbox, contactbox, links_rail

CRUMB = {"/kennisbank/": "Kennisbank"}


def _p(url, title, h1, description, intro, blocks, rail, prio="0.6"):
    return {"url": url, "title": title, "h1": h1, "description": description,
            "intro": intro, "blocks": blocks, "rail": rail, "priority": prio,
            "crumb_labels": CRUMB}


def _rail(exclude):
    items = [x for x in KENNIS_LINKS if x[0] != exclude][:6]
    return [links_rail("Kennisbank", items),
            ("dark", "Situaties", '<p>De praktische kant per situatie staat onder <a href="/ontruimen/">soorten ontruimingen</a>, de bedragen op de <a href="/kosten/">kostenpagina</a>.</p>'),
            contactbox()]


def pages():
    out = []

    out.append(_p(
        "/kennisbank/",
        "Kennisbank woningontruiming: regels, termijnen en begrippen | SpoedWoningOntruiming.nl",
        "Kennisbank",
        "Uitleg over de regels rond ontruimen: erfrecht, huurrecht, oplevering, afvalregels, asbest, hergebruik en de begrippen die in offertes voorkomen.",
        "De juridische en praktische achtergrond bij een ontruiming, per onderwerp uitgelegd en met verwijzing naar de wetsartikelen en officiële bronnen.",
        [
            ("h2", "Erfrecht en nalatenschap"),
            ("cards", [
                ("/kennisbank/erfenis-aanvaarden/", "Erfenis aanvaarden of verwerpen",
                 "Zuiver, beneficiair of verwerpen, en welke handelingen in de woning tot zuivere aanvaarding leiden."),
                ("/kennisbank/verklaring-van-erfrecht/", "Verklaring van erfrecht",
                 "Wanneer dit document nodig is, wat het kost en welke uitzonderingen banken hanteren."),
                ("/kennisbank/waardevolle-spullen/", "Waardevolle spullen herkennen",
                 "Edelmetaal, horloges, munten en design, en de plekken waar geld en papieren zich verstoppen."),
            ], 3),
            ("h2", "Huur en oplevering"),
            ("cards", [
                ("/kennisbank/huur-opzeggen-na-overlijden/", "Huur opzeggen na overlijden",
                 "Artikel 7:268 BW, de tweede maand na het overlijden en de positie van medehuurders."),
                ("/kennisbank/oplevering-en-beschrijving/", "Oplevering en beschrijving",
                 "Artikel 7:224 BW, het wettelijk vermoeden zonder beschrijving en de rol van de voorinspectie."),
                ("/kennisbank/zelf-aangebrachte-voorzieningen/", "Zelf aangebrachte voorzieningen",
                 "Wat blijft zitten, wat eruit moet en wanneer een verhuurder een vergoeding verschuldigd is."),
            ], 3),
            ("h2", "Afval, veiligheid en hergebruik"),
            ("cards", [
                ("/kennisbank/grofvuil-en-milieustraat/", "Grofvuil en milieustraat",
                 "Wat een gemeente aanneemt, welke limieten er gelden en wat er niet in de gewone stroom mag."),
                ("/kennisbank/asbest-in-de-woning/", "Asbest in de woning",
                 "Bouwjaar, de grens van 35 vierkante meter, de meldplicht en wanneer een gecertificeerd bedrijf verplicht is."),
                ("/kennisbank/hergebruik-en-kringloop/", "Hergebruik en kringloop",
                 "Wat kringloopwinkels aannemen, wat er landelijk hergebruikt wordt en waar textiel en elektronica heen gaan."),
            ], 3),
            ("h2", "Naslag"),
            ("cards", [
                ("/kennisbank/begrippenlijst/", "Begrippenlijst",
                 "Vijfendertig termen uit offertes, huurcontracten en inspectierapporten, kort uitgelegd."),
            ], 3),
        ],
        [links_rail("Onderwerpen", KENNIS_LINKS[:7]),
         ("dark", "Praktisch", '<p>Stap voor stap door een traject: de <a href="/checklists/">checklists</a>. Een bedrag uitrekenen: de <a href="/tools/">tools</a>.</p>'),
         contactbox()],
        prio="0.8",
    ))

    # ------------------------------------------------------------ erfenis
    out.append(_p(
        "/kennisbank/erfenis-aanvaarden/",
        "Erfenis aanvaarden of verwerpen en het leeghalen van de woning | SpoedWoningOntruiming.nl",
        "Erfenis aanvaarden of verwerpen",
        "Zuiver aanvaarden, beneficiair aanvaarden en verwerpen, en welke handelingen in de woning van een overledene tot persoonlijke aansprakelijkheid leiden.",
        "Wie spullen uit de woning van een overledene meeneemt, kan daarmee ongemerkt de erfenis aanvaarden en persoonlijk aansprakelijk worden voor de schulden. De grens ligt precies tussen beheren en beschikken.",
        [
            ("h2", "Drie keuzes"),
            ("table", ["Keuze", "Gevolg", "Hoe"], [
                ["Zuiver aanvaarden", "Alle bezittingen en alle schulden, ook wanneer de schulden groter zijn dan het bezit. Schulden komen dan uit het eigen vermogen.",
                 "Gebeurt vanzelf door gedrag, of met een verklaring bij de rechtbank"],
                ["Beneficiair aanvaarden", "Erfgenaam is alleen aansprakelijk tot de omvang van de nalatenschap. Wel een wettelijke vereffeningsprocedure.",
                 "Verklaring bij de griffie van de rechtbank, tegen griffierecht"],
                ["Verwerpen", "Geen bezittingen, geen schulden. De erfgenaam wordt geacht nooit erfgenaam te zijn geweest.",
                 "Verklaring bij de griffie van de rechtbank, tegen griffierecht"],
            ]),
            ("p", "Wie twijfelt over de omvang van de schulden, kiest voor beneficiair aanvaarden. Dat is de veilige middenweg en kan zolang er nog geen zuivere aanvaarding heeft plaatsgevonden."),
            ("h2", "De wettekst"),
            ("p", "Artikel 4:192 lid 1 van het Burgerlijk Wetboek: een erfgenaam aanvaardt de nalatenschap zuiver wanneer hij zich ondubbelzinnig en zonder voorbehoud als een zuiver aanvaard hebbende erfgenaam gedraagt doordat hij overeenkomsten aangaat strekkende tot vervreemding of bezwaring van goederen van de nalatenschap of deze op andere wijze aan het verhaal van schuldeisers onttrekt."),
            ("p", "Dat criterium is in 2016 versmald door de Wet bescherming erfgenamen tegen schulden. Sindsdien is niet elke handeling in de woning risicovol. Bepalend is of iets wordt onttrokken aan schuldeisers."),
            ("h2", "Beheren tegenover beschikken"),
            ("table", ["Wel toegestaan, dit is beheer", "Niet doen, dit is beschikken"], [
                ["De woning leeghalen en schoonmaken", "Meubels of sieraden verdelen onder familie"],
                ["Inboedelgoederen opslaan", "De auto of de inboedel verkopen"],
                ["Spullen zonder economische waarde afvoeren naar kringloop of verwerker", "Een waardevol horloge of schilderij meenemen"],
                ["De uitvaart regelen en betalen uit het saldo", "Rekeningen van de overledene selectief betalen uit eigen geld"],
                ["Post openen en administratie ordenen", "Een lopend abonnement of contract overzetten op eigen naam"],
            ]),
            ("warn", "De praktische regel",
             "<p>Alles wat verkoopbaar is, blijft staan of gaat naar een afgesloten opslag totdat de keuze over de nalatenschap is gemaakt. Alles wat evident geen waarde heeft, mag weg. Bij twijfel over een voorwerp: fotograferen en laten staan.</p>"),
            ("h2", "Termijn"),
            ("p", "Er staat geen harde wettelijke termijn op de keuze, maar de kantonrechter kan op verzoek van een belanghebbende, bijvoorbeeld een schuldeiser of de verhuurder, een termijn stellen. En de huurovereenkomst loopt intussen af aan het eind van de tweede maand na het overlijden, wat in de praktijk de echte deadline is."),
            ("p", "Wie na een zuivere aanvaarding wordt geconfronteerd met een onbekende schuld, kan de kantonrechter binnen drie maanden na de ontdekking vragen alsnog beneficiair te mogen aanvaarden. Dat is een uitzondering en geen vangnet."),
            ("h2", "Als iedereen verwerpt"),
            ("p", "Verwerpen alle erfgenamen, dan is er niemand die de woning hoeft leeg te halen. De verhuurder ruimt in dat geval zelf en verhaalt de kosten op de nalatenschap. Blijft daar niets van over, dan draagt de verhuurder de kosten. Een kantonrechter kan een vereffenaar benoemen wanneer er wel bezit is maar geen erfgenaam die het afwikkelt."),
            ("h2", "Waar te melden"),
            ("p", "De verklaring van aanvaarding of verwerping gaat naar de griffie van de rechtbank in het arrondissement waar de overledene woonde. Informatie en formulieren staan op https://www.rechtspraak.nl. Het boedelregister waarin de verklaringen worden opgenomen, is bij diezelfde rechtbank in te zien."),
            ("h2", "Veelgestelde vragen"),
            ("faq", [
                ("Mag de woning leeggehaald worden voor de keuze is gemaakt?",
                 "<p>Ja, zolang het bij beheer blijft: ruimen, opslaan en afvoeren van waardeloze zaken. Verkopen of verdelen niet.</p>"),
                ("Telt het betalen van de uitvaart als zuiver aanvaarden?",
                 "<p>Nee. Het regelen en betalen van de uitvaart wordt niet gezien als zuivere aanvaarding.</p>"),
                ("Wat kost beneficiair aanvaarden?",
                 "<p>Griffierecht bij de rechtbank, een bedrag van enkele tientallen tot ruim honderd euro per verklaring. Een notaris of advocaat inschakelen kost extra.</p>"),
                ("Geldt dit ook voor kleinkinderen?",
                 "<p>Ja. Wanneer een kind verwerpt, komen diens kinderen in de plaats. Minderjarigen aanvaarden altijd beneficiair.</p>"),
            ]),
        ],
        _rail("/kennisbank/erfenis-aanvaarden/"),
        prio="0.7",
    ))

    # ------------------------------------------------------------ huur opzeggen
    out.append(_p(
        "/kennisbank/huur-opzeggen-na-overlijden/",
        "Huur opzeggen na overlijden: termijnen uit artikel 7:268 BW | SpoedWoningOntruiming.nl",
        "Huur opzeggen na overlijden",
        "Wanneer de huurovereenkomst eindigt na het overlijden van de huurder, wat medehuurders en achterblijvers kunnen, en welke termijnen gelden.",
        "Na het overlijden van een alleenwonende huurder loopt de huur korter door dan veel nabestaanden denken. De wet regelt dat in artikel 7:268 van het Burgerlijk Wetboek, met verschillende uitkomsten per situatie.",
        [
            ("h2", "Vier situaties"),
            ("table", ["Situatie", "Wat er gebeurt"], [
                ["Er is een medehuurder", "De medehuurder zet de huur voort als huurder. Hij kan binnen zes maanden na het overlijden opzeggen, met ingang van de eerste dag van de tweede maand na die opzegging."],
                ["Er is een achterblijver met duurzame gemeenschappelijke huishouding", "Deze zet de huur zes maanden voort. Binnen die termijn kan hij de rechter vragen de huur daarna te mogen voortzetten."],
                ["Er is niemand die de huur voortzet", "De huur eindigt van rechtswege aan het eind van de tweede maand na het overlijden."],
                ["Erfgenamen willen eerder van de huur af", "Zij kunnen de huur laten eindigen tegen het eind van de eerste maand na het overlijden."],
            ]),
            ("p", "De laatste twee regels staan in lid 6 van het artikel. Ze betekenen concreet: bij een overlijden op 12 maart loopt de huur zonder actie door tot en met 31 mei, en met een opzegging door de erfgenamen tot en met 30 april."),
            ("note", "Wat er direct geregeld moet worden",
             "<p>Melding bij de verhuurder met een kopie van de overlijdensakte, en meteen vragen naar de voorinspectie en het opleverformulier. Corporaties plannen die inspectie doorgaans binnen twee weken, en dat rapport bepaalt wat er bij de ontruiming moet gebeuren.</p>"),
            ("h2", "Medehuurder tegenover achterblijver"),
            ("p", "Een medehuurder staat in het contract of is door de verhuurder of de rechter als medehuurder erkend. Een echtgenoot of geregistreerd partner is van rechtswege medehuurder zolang de woning het hoofdverblijf is. Een samenwonende partner zonder registratie is dat niet automatisch, en moet dan het pad van de duurzame gemeenschappelijke huishouding bewandelen."),
            ("p", "Inwonende kinderen worden zelden aangemerkt als duurzame gemeenschappelijke huishouding, omdat de rechter de samenwoning als aflopend beschouwt: een kind wordt geacht op termijn zelfstandig te gaan wonen. Uitzonderingen bestaan, bijvoorbeeld bij langdurige mantelzorg, maar dat vraagt bewijs."),
            ("h2", "Wat de verhuurder mag verlangen"),
            ("ul", [
                "Oplevering volgens het huurcontract en het voorinspectierapport, dus meestal leeg, bezemschoon en zonder zelf aangebrachte voorzieningen die eruit moeten.",
                "Huur tot en met de einddatum, ook wanneer de woning eerder leeg is. Sommige corporaties verrekenen wel bij vroege oplevering.",
                "Alle sleutels, ook van berging, garagebox en fietsenstalling.",
                "Bij niet-tijdige oplevering: doorlopende huur plus schadevergoeding, of kosten van een ontruiming die de verhuurder zelf laat uitvoeren.",
            ]),
            ("h2", "Als de erfgenamen niets doen"),
            ("p", "De huurovereenkomst eindigt hoe dan ook aan het eind van de tweede maand. Staat de woning dan nog vol, dan kan de verhuurder de ontruiming zelf laten uitvoeren en de kosten indienen bij de nalatenschap. Bij een lege nalatenschap blijft de rekening bij de verhuurder. Voor erfgenamen die beneficiair hebben aanvaard of verworpen, levert dat geen persoonlijke aansprakelijkheid op."),
            ("h2", "Sociale huur en de wachtlijst"),
            ("p", "Bij corporaties komt de woning na de einddatum in de verhuur. Dat is de reden dat corporaties strak op de datum sturen: elke week leegstand kost huurinkomsten en houdt een woningzoekende op. Een verzoek om uitstel wordt soms gehonoreerd, maar dan tegen doorlopende huur."),
            ("h2", "Veelgestelde vragen"),
            ("faq", [
                ("Moet de huur schriftelijk worden opgezegd?",
                 "<p>Voor de verkorting naar het eind van de eerste maand wel. Zonder opzegging eindigt de huur automatisch aan het eind van de tweede maand.</p>"),
                ("Kan de verhuurder een langere opzegtermijn eisen?",
                 "<p>Nee. Artikel 7:268 is dwingend recht bij woonruimte, een afwijkende contractbepaling in het nadeel van de huurder is niet geldig.</p>"),
                ("Hoe zit het met een woning van een particuliere verhuurder?",
                 "<p>Dezelfde regels. Het onderscheid tussen corporatie en particuliere verhuurder maakt voor dit artikel niet uit.</p>"),
                ("Wat gebeurt er met de huurtoeslag?",
                 "<p>Die stopt per de maand na het overlijden. Te veel ontvangen toeslag wordt teruggevorderd bij de nalatenschap, zie https://www.toeslagen.nl.</p>"),
            ]),
        ],
        _rail("/kennisbank/huur-opzeggen-na-overlijden/"),
        prio="0.7",
    ))

    # ------------------------------------------------------------ verklaring erfrecht
    out.append(_p(
        "/kennisbank/verklaring-van-erfrecht/",
        "Verklaring van erfrecht: wanneer nodig en wat het kost | SpoedWoningOntruiming.nl",
        "Verklaring van erfrecht",
        "Wat een verklaring van erfrecht is, wanneer banken en notarissen erom vragen, welke bedragen gelden en hoe lang het opstellen duurt.",
        "Een verklaring van erfrecht is een notariële akte waarin staat wie er is overleden, wie de erfgenamen zijn en wie namens hen mag handelen. Zonder dat document blijft een bankrekening geblokkeerd en kan een woning niet worden overgedragen.",
        [
            ("h2", "Wanneer het document nodig is"),
            ("check", [
                "Bij de verkoop of overdracht van een woning uit de nalatenschap.",
                "Wanneer er een testament is met een executeur of een afwijkende erfstelling.",
                "Bij een saldo boven de grens die de bank hanteert.",
                "Wanneer er meerdere erfgenamen zijn en een van hen namens de rest moet kunnen handelen.",
                "Bij een overledene die minderjarig was, onder curatele stond, in schuldsanering zat of failliet was verklaard.",
                "Bij beleggingsrekeningen, effecten of een lopende hypotheek.",
            ]),
            ("h2", "Wanneer het niet nodig is"),
            ("p", "Banken hanteren uitzonderingen. Voor een langstlevende echtgenoot of geregistreerd partner vragen zij doorgaans geen verklaring wanneer het saldo niet boven de honderdduizend euro uitkomt. Voor andere erfgenamen ligt de grens lager, vaak rond tienduizend euro. De precieze grens verschilt per bank, dus navragen bij de bank zelf is de kortste route."),
            ("p", "In plaats van een verklaring vragen banken dan om een overlijdensakte, een identiteitsbewijs, een verklaring uit het Centraal Testamentenregister en een vrijwaringsformulier."),
            ("h2", "Kosten en doorlooptijd"),
            ("table", ["Onderdeel", "Indicatie 2026"], [
                ["Eenvoudige verklaring, een of twee erfgenamen", "Vanaf ongeveer 395 tot 500 euro"],
                ["Meerdere erfgenamen of een testament met executeur", "600 tot 900 euro"],
                ["Complexe situatie, buitenlandse erfgenamen of bedrijf in de nalatenschap", "1.000 euro en hoger"],
                ["Doorlooptijd", "Een tot drie weken, afhankelijk van de reactietijd van de erfgenamen"],
            ]),
            ("p", "Bedragen zijn indicatief en verschillen per notaris. Tarieven van notarissen zijn vrij, dus offertes vergelijken loont. Een overzicht van notarissen staat op https://www.notaris.nl."),
            ("h2", "Wat erin staat"),
            ("ul", [
                "Wie is overleden en wanneer.",
                "Of er een testament is en wat daarin over de erfstelling staat.",
                "Wie de erfgenamen zijn en of zij hebben aanvaard of verworpen.",
                "Wie bevoegd is namens de nalatenschap te handelen, bijvoorbeeld een executeur of een gevolmachtigde.",
            ]),
            ("h2", "Verklaring van executele"),
            ("p", "Is er een executeur benoemd, dan volstaat vaak een verklaring van executele. Die is beperkter en daarmee sneller en minder duur: hij bevestigt alleen dat iemand executeur is en bevoegd is de nalatenschap te beheren. Voor de verkoop van een woning is doorgaans alsnog een volledige verklaring van erfrecht nodig."),
            ("note", "Volgorde bij een woning",
             "<p>Bij een koopwoning uit een nalatenschap loopt de verkoop pas wanneer de verklaring er is. Het aanvragen kan al starten voordat de woning leeg is, en dat scheelt weken doorlooptijd waarin hypotheeklasten en heffingen doorlopen.</p>"),
            ("h2", "Veelgestelde vragen"),
            ("faq", [
                ("Is een verklaring van erfrecht verplicht?",
                 "<p>Niet wettelijk. Banken, notarissen en instanties vragen erom, en zonder dat document weigeren zij mee te werken.</p>"),
                ("Hoe lang is de verklaring geldig?",
                 "<p>Er staat geen vervaldatum op. Sommige instanties vragen om een exemplaar dat niet ouder is dan zes maanden of een jaar.</p>"),
                ("Kan de verklaring worden aangevraagd voordat de erfenis is aanvaard?",
                 "<p>De notaris legt de keuze juist vast in de akte, dus de keuze moet bekend zijn. Wie beneficiair wil aanvaarden, doet dat eerst bij de rechtbank.</p>"),
                ("Wie betaalt de notariskosten?",
                 "<p>De nalatenschap, mits daar saldo is. Anders schieten de erfgenamen voor.</p>"),
            ]),
        ],
        _rail("/kennisbank/verklaring-van-erfrecht/"),
    ))

    # ------------------------------------------------------------ oplevering
    out.append(_p(
        "/kennisbank/oplevering-en-beschrijving/",
        "Oplevering en beschrijving: artikel 7:224 BW uitgelegd | SpoedWoningOntruiming.nl",
        "Oplevering en beschrijving",
        "Hoe artikel 7:224 BW de opleververplichting regelt, wat het wettelijk vermoeden zonder beschrijving betekent en waarom de voorinspectie beslissend is.",
        "Bij een discussie over de oplevering van een huurwoning draait vrijwel alles om twee documenten: de beschrijving uit de begintijd en het voorinspectierapport uit de eindfase.",
        [
            ("h2", "De wettekst"),
            ("p", "Artikel 7:224 lid 1 van het Burgerlijk Wetboek: de huurder is verplicht het gehuurde bij het einde van de huur weer ter beschikking van de verhuurder te stellen."),
            ("p", "Lid 2: is tussen huurder en verhuurder een beschrijving van het verhuurde opgemaakt, dan moet de huurder de zaak opleveren in dezelfde staat waarin deze volgens die beschrijving is aanvaard, met uitzondering van geoorloofde veranderingen en toevoegingen en van wat door ouderdom is tenietgegaan of beschadigd. Is er geen beschrijving opgemaakt, dan wordt de huurder, behoudens tegenbewijs, verondersteld het gehuurde te hebben ontvangen in de staat waarin dat zich bevindt bij het einde van de huurovereenkomst."),
            ("h2", "Wat dat vermoeden waard is"),
            ("p", "Zonder beschrijving ligt de bewijslast bij de verhuurder. Hij moet dan aantonen dat de woning bij aanvang in een betere staat verkeerde, bijvoorbeeld met foto's of een verklaring. Lukt dat niet, dan kan hij geen herstelkosten claimen. Dat maakt het opzoeken van het oude opnameformulier de belangrijkste handeling van de hele oplevering."),
            ("note", "Waar het formulier vaak ligt",
             "<p>Bij het huurcontract in de administratie, in het huurdersportaal van de corporatie, of bij de corporatie zelf op te vragen. Corporaties bewaren opnameformulieren doorgaans digitaal en verstrekken op verzoek een kopie.</p>"),
            ("h2", "Normale slijtage"),
            ("p", "Wat door ouderdom versleten of beschadigd is, valt buiten de verplichting. Verkleurd behang na tien jaar, een versleten keukenblad of doorgelopen verf op een kozijn hoeven niet hersteld te worden. Een gat in een deur, een gebroken tegel of een brandplek in het aanrechtblad wel, want dat is schade en geen slijtage."),
            ("h2", "De voorinspectie in de praktijk"),
            ("p", "De verhuurder houdt enkele weken voor het einde van de huur een voorinspectie. Dat rapport is de opdrachtlijst. Punten die er niet in staan, kan de verhuurder later moeilijk alsnog eisen."),
            ("p", "Voert de verhuurder geen voorinspectie uit, dan kan hij in beginsel alleen de kosten vorderen die de huurder zelf zou hebben gemaakt om het gebrek te herstellen. Dat betekent materiaalkosten, en niet het uurtarief van een aannemer. Dat scheelt in de praktijk het grootste deel van de rekening."),
            ("h2", "De eindinspectie"),
            ("check", [
                "Loop het voorinspectierapport punt voor punt langs met de inspecteur erbij.",
                "Laat afwijkingen ter plaatse noteren, niet achteraf per mail.",
                "Maak foto's van elke ruimte, met datum, voordat de sleutel wordt afgegeven.",
                "Noteer de meterstanden van gas, water en elektra en laat die aftekenen.",
                "Vraag om een ondertekend exemplaar van het opleverformulier.",
                "Lever alle sleutels in en laat het aantal noteren.",
            ]),
            ("h2", "Als er toch een rekening komt"),
            ("p", "Een verhuurder die achteraf kosten in rekening brengt, moet die onderbouwen met het inspectierapport en met facturen. Bij een geschil over sociale huur kan de zaak worden voorgelegd aan de klachtencommissie van de corporatie, en daarna aan de Huurcommissie of de kantonrechter. Informatie staat op https://www.huurcommissie.nl."),
            ("h2", "Veelgestelde vragen"),
            ("faq", [
                ("Mag een verhuurder eisen dat de woning geschilderd wordt?",
                 "<p>Alleen wanneer dat volgt uit het contract of uit afwijkende kleuren die niet als geoorloofde verandering gelden. Normale slijtage van verf hoeft niet te worden hersteld.</p>"),
                ("Wat als de verhuurder de voorinspectie steeds uitstelt?",
                 "<p>Vraag de inspectie schriftelijk aan en bewaar die correspondentie. Bij het uitblijven ervan staat de huurder sterker in een latere discussie.</p>"),
                ("Telt een videorondje als bewijs?",
                 "<p>Ja, mits de datum vaststaat. Een video met zichtbare metadata of een e-mail waarin de opname op datum is verstuurd, werkt goed.</p>"),
            ]),
        ],
        _rail("/kennisbank/oplevering-en-beschrijving/"),
    ))

    # ------------------------------------------------------------ ZAV
    out.append(_p(
        "/kennisbank/zelf-aangebrachte-voorzieningen/",
        "Zelf aangebrachte voorzieningen bij oplevering | SpoedWoningOntruiming.nl",
        "Zelf aangebrachte voorzieningen",
        "Wat een huurder zelf heeft aangebracht mag blijven zitten, wat eruit moet en wanneer er recht op een vergoeding bestaat.",
        "Een zelf geplaatste keuken, een dakkapel, laminaat of een tuinhuis vallen onder de zelf aangebrachte voorzieningen. Bij de oplevering wordt per voorziening bepaald of die blijft, weg moet of wordt overgenomen.",
        [
            ("h2", "Het uitgangspunt"),
            ("p", "Een huurder mag de woning naar eigen inzicht inrichten en veranderingen aanbrengen die zonder noemenswaardige kosten ongedaan te maken zijn. Voor ingrijpender veranderingen is toestemming van de verhuurder nodig. Bij het einde van de huur heeft de huurder een wegneemrecht: hij mag wat hij heeft aangebracht meenemen, mits hij de woning in de oude staat terugbrengt."),
            ("p", "Corporaties werken met ZAV-beleid, een reglement waarin per soort voorziening staat wat is toegestaan, wat gemeld moet worden en wat bij vertrek gebeurt. Dat reglement is bij de corporatie op te vragen en is bepalend voor de oplevering."),
            ("h2", "Drie uitkomsten"),
            ("table", ["Uitkomst", "Wanneer", "Gevolg"], [
                ["Blijft zitten zonder vergoeding", "De voorziening is netjes uitgevoerd en bruikbaar voor de volgende huurder",
                 "Geen kosten, geen opbrengst"],
                ["Moet verwijderd worden", "Geen toestemming gevraagd, slecht uitgevoerd of niet bruikbaar",
                 "Verwijderen en de oude staat herstellen, op kosten van de huurder"],
                ["Wordt overgenomen", "De corporatie of de volgende huurder neemt de voorziening over",
                 "Soms een vergoeding, meestal op basis van afschrijving"],
            ]),
            ("h2", "Wat er vaak speelt bij een ontruiming"),
            ("ul", [
                "Laminaat en vloerbedekking: bij veel corporaties toegestaan om te blijven liggen als de vloer in goede staat is, anders eruit inclusief lijmresten.",
                "Een zelf geplaatste keuken: blijft vaak zitten wanneer die beter is dan de standaardkeuken, en moet eruit wanneer aansluitingen zijn verlegd.",
                "Een tuinhuis of schuur: vergunningplicht en fundering bepalen of die kan blijven. Zonder toestemming meestal afbreken.",
                "Zonwering, screens en airco: buitenunits en boorgaten in de gevel zijn een standaardpunt bij de eindinspectie.",
                "Verwijderde binnenmuren of doorbraken: bijna altijd terugbouwen, tenzij er schriftelijke toestemming ligt.",
                "Spots en verlaagde plafonds: vaak weg, inclusief het herstellen van het originele plafond.",
            ]),
            ("note", "De papieren zijn beslissend",
             "<p>Een schriftelijke toestemming uit het verleden verandert de uitkomst volledig. Zoek in de administratie naar brieven of e-mails van de verhuurder over de klus. Bij corporaties is een aanvraag doorgaans in het dossier terug te vinden.</p>"),
            ("h2", "Vergoeding"),
            ("p", "Een huurder heeft recht op vergoeding wanneer de verhuurder ongerechtvaardigd wordt verrijkt door een voorziening die achterblijft. In de praktijk hanteren corporaties een afschrijvingstabel, waarbij een keuken bijvoorbeeld in tien tot vijftien jaar wordt afgeschreven. Na die periode is de vergoeding nul, ook wanneer de voorziening nog goed is."),
            ("h2", "Bij een overleden huurder"),
            ("p", "Erfgenamen treden in de positie van de huurder. Zij kunnen dus ook een beroep doen op overname van voorzieningen of op een vergoeding, en zij dragen de plicht om niet-toegestane voorzieningen te verwijderen. Dat laatste is bij een ontruiming na overlijden regelmatig een kostenpost die vooraf niet is meegenomen."),
            ("h2", "Veelgestelde vragen"),
            ("faq", [
                ("Moet laminaat er altijd uit?",
                 "<p>Nee. Veel corporaties laten een nette vloer liggen. Het voorinspectierapport is bepalend, dus vraag het daar expliciet na.</p>"),
                ("Wat als de vorige huurder de voorziening heeft aangebracht?",
                 "<p>Dan geldt wat er bij de overname is vastgelegd. Zonder papieren wordt de huidige huurder er vaak op aangesproken.</p>"),
                ("Kan een corporatie een keuken laten verwijderen die beter is dan de hare?",
                 "<p>Ja, wanneer er geen toestemming voor was of wanneer aansluitingen zijn verlegd. In de praktijk gebeurt dat zelden bij een net uitgevoerde keuken.</p>"),
            ]),
        ],
        _rail("/kennisbank/zelf-aangebrachte-voorzieningen/"),
    ))

    # ------------------------------------------------------------ grofvuil
    out.append(_p(
        "/kennisbank/grofvuil-en-milieustraat/",
        "Grofvuil en milieustraat: regels, limieten en tarieven | SpoedWoningOntruiming.nl",
        "Grofvuil en milieustraat",
        "Wat een gemeente aan grofvuil aanneemt, welke limieten er gelden, wat er apart moet en waarom een complete woninginhoud er niet onder valt.",
        "Zelf afvoeren kan, maar niet ongelimiteerd. Gemeenten stellen per keer een maximum aan grofvuil, en de milieustraat is bedoeld voor huishoudelijk afval van particulieren, niet voor een volledige woninginhoud.",
        [
            ("h2", "Twee routes"),
            ("table", ["Route", "Hoe het werkt", "Beperking"], [
                ["Grofvuil laten ophalen", "Online of telefonisch aanmelden bij de gemeente of de afvaldienst, waarna er een ophaaldag volgt",
                 "Maximum aantal stuks of kubieke meters per keer, wachttijd van dagen tot enkele weken"],
                ["Zelf brengen naar de milieustraat", "Op vertoon van een afvalpas of legitimatie met adres",
                 "Vaak een aantal vrije bezoeken per jaar, daarna per keer of per kubieke meter betalen"],
            ]),
            ("p", "De tarieven en limieten verschillen sterk per gemeente. De afvalstoffenheffing stijgt in 2026 met ongeveer 3,6 procent volgens een steekproef van Vereniging Eigen Huis onder 106 gemeenten, na 5 procent in 2025 en 6 procent in 2024. De spreiding tussen gemeenten is groot, van ruim tweehonderd tot boven de vijfhonderdvijftig euro per huishouden per jaar."),
            ("h2", "Wat apart moet"),
            ("ul", [
                "Elektrische apparaten en witgoed: gescheiden inleveren, koelapparatuur vraagt aftappen van koudemiddel door een gecertificeerd bedrijf.",
                "Tl-buizen en spaarlampen: kwikhoudend, aparte inzameling.",
                "Verf, oplosmiddelen, accu's, batterijen en gasflessen: klein chemisch afval, apart inleveren.",
                "Autobanden, gipsplaten en dakleer: bij veel milieustraten aparte stromen met een eigen tarief.",
                "Asbestverdacht materiaal: alleen na melding en dubbel verpakt, zie de pagina over " + '<a href="/kennisbank/asbest-in-de-woning/">asbest in de woning</a>.',
                "Medicijnen en injectienaalden: via apotheek of huisarts, niet bij het huisvuil.",
            ]),
            ("warn", "Bedrijfsafval valt erbuiten",
             "<p>Milieustraten zijn er voor particulieren. Afval uit een bedrijfspand, of een woninginhoud die door een bedrijf wordt afgevoerd, gaat naar een commerciële verwerker en wordt per ton afgerekend. Een ontruimingsbedrijf dat afval als particulier huishoudelijk afval aanbiedt, doet dat niet volgens de regels.</p>"),
            ("h2", "Wat een woninginhoud aan volume betekent"),
            ("p", "Een tweekamerappartement komt vaak uit op vijftien tot vijfentwintig kubieke meter, een eengezinswoning op dertig tot vijftig. Een bakwagen neemt ongeveer twintig kubieke meter mee, een gewone bestelbus rond de acht. Een grofvuilronde neemt bij veel gemeenten twee tot drie kubieke meter per keer aan. Daaruit volgt vanzelf waarom zelf afvoeren bij een hele woning meerdere weken kost."),
            ("p", "Een schatting van het volume in een concrete situatie geeft de %s."
             % '<a href="/tools/inboedelvolume/">volumecalculator</a>'),
            ("h2", "Kosten in beeld"),
            ("table", ["Post", "Indicatie"], [
                ["Grofvuil ophalen door de gemeente", "0 tot 60 euro per keer, sterk verschillend per gemeente"],
                ["Milieustraat, boven het vrije aantal bezoeken", "10 tot 40 euro per bezoek of per kubieke meter"],
                ["Afvalcontainer 6 kubieke meter", "250 tot 400 euro inclusief plaatsen en verwerken"],
                ["Afvalcontainer 10 kubieke meter", "300 tot 500 euro inclusief plaatsen en verwerken"],
                ["Vergunning containerplaatsing", "0 tot 100 euro, afhankelijk van de gemeente"],
            ]),
            ("h2", "Veelgestelde vragen"),
            ("faq", [
                ("Kan grofvuil zomaar aan de straat?",
                 "<p>Nee. Zonder aanmelding levert dat in de meeste gemeenten een boete op wegens verkeerd aanbieden van afval.</p>"),
                ("Neemt de milieustraat een complete inboedel aan?",
                 "<p>Niet in een keer. Er gelden limieten per bezoek, en een woninginhoud valt buiten de bedoeling van de voorziening.</p>"),
                ("Wat gebeurt er met bruikbare spullen?",
                 "<p>Veel milieustraten hebben een kringloophoek. Rechtstreeks naar een kringloopwinkel brengen levert een grotere kans op hergebruik op.</p>"),
                ("Is een container vergunningplichtig?",
                 "<p>Op eigen terrein niet, op de openbare weg meestal wel. De gemeente beslist en rekent soms precariokosten.</p>"),
            ]),
        ],
        _rail("/kennisbank/grofvuil-en-milieustraat/"),
    ))

    # ------------------------------------------------------------ asbest
    out.append(_p(
        "/kennisbank/asbest-in-de-woning/",
        "Asbest in de woning bij een ontruiming: regels en grenzen | SpoedWoningOntruiming.nl",
        "Asbest in de woning",
        "Waar asbest in oudere woningen zit, wat een particulier zelf mag verwijderen, welke meldingen verplicht zijn en wanneer een gecertificeerd bedrijf nodig is.",
        "Woningen van voor 1994 kunnen asbest bevatten. Bij een ontruiming komt dat vooral naar boven wanneer vloerbedekking, zeil of plafondplaten eruit moeten. De regels zijn strikt, en de meldplicht loopt via de gemeente.",
        [
            ("h2", "Waar het zit"),
            ("p", "Asbest is in Nederland verboden sinds 1993, met een overgang naar 1994. In woningen van voor die tijd komt het op vaste plekken voor:"),
            ("ul", [
                "Vinylzeil met een viltachtige onderlaag, vaak in keuken, hal en badkamer.",
                "Vloertegels van het type dat in de jaren zestig en zeventig veel is gelegd.",
                "Golfplaten op schuurdaken en overkappingen.",
                "Standleidingen, rioolbuizen en ventilatiekanalen.",
                "Plaatmateriaal achter de cv-ketel, in meterkasten en rond schoorsteenkanalen.",
                "Bloembakken en vensterbanken van geperst materiaal.",
            ]),
            ("h2", "Wat een particulier zelf mag"),
            ("p", "Een particulier mag onder voorwaarden tot 35 vierkante meter asbesthoudend materiaal uit de eigen woning verwijderen. Dat geldt alleen voor geschroefde, hechtgebonden platen die heel blijven, voor vloertegels en niet-gelijmde vloerbedekking die in zijn geheel verwijderd wordt, en voor losse voorwerpen die goed verpakt worden. Geen daklei, geen gelijmd materiaal, geen verweerd of gebroken asbest, en niet uit andere bouwwerken dan de eigen woning."),
            ("warn", "Melden is verplicht",
             "<p>Verwijdering vraagt een sloopmelding via het Omgevingsloket, minimaal een week vooraf. Daarna volgt een startmelding minstens twee dagen voor de werkzaamheden en een gereedmelding op de eerste werkdag erna. De gemeente kan aanvullende eisen stellen. Informatie staat op https://iplo.nl en bij de eigen gemeente.</p>"),
            ("h2", "Wanneer een gecertificeerd bedrijf verplicht is"),
            ("check", [
                "Bij niet-hechtgebonden asbest, zoals spuitasbest of isolatiemateriaal rond leidingen.",
                "Bij gelijmde vloerbedekking of gelijmde tegels.",
                "Bij beschadigd, verweerd of gebroken materiaal.",
                "Bij meer dan 35 vierkante meter.",
                "Bij huurwoningen: de huurder mag niet zelf verwijderen, dat loopt via de verhuurder.",
                "Bij bedrijfspanden en bij alles wat niet de eigen woning is.",
            ]),
            ("h2", "Wat dit betekent bij een ontruiming"),
            ("p", "Een ontruimingsbedrijf zonder asbestcertificaat mag geen asbest verwijderen. Wordt er tijdens de werkzaamheden asbestverdacht materiaal aangetroffen, dan wordt het werk stilgelegd en volgt eerst een inventarisatie door een gecertificeerd bureau. Dat kost dagen en geld, en het is de reden dat een opname bij oudere woningen ook naar de vloeropbouw kijkt."),
            ("p", "Bij een huurwoning is de verhuurder verantwoordelijk voor asbest in het gehuurde. Een corporatie beschikt vaak al over een asbestinventarisatie van het complex. Die opvragen voordat de vloer eruit gaat, voorkomt een stillegging."),
            ("h2", "Kosten"),
            ("table", ["Onderdeel", "Indicatie"], [
                ["Asbestinventarisatie type A", "400 tot 900 euro voor een woning"],
                ["Verwijdering vloerzeil door een gecertificeerd bedrijf", "50 tot 120 euro per vierkante meter"],
                ["Verwijdering golfplaten schuurdak", "20 tot 45 euro per vierkante meter"],
                ["Storten van verpakt asbest", "Aparte stroom met een eigen tarief, vaak per big bag"],
            ]),
            ("h2", "Veelgestelde vragen"),
            ("faq", [
                ("Hoe blijkt of iets asbest bevat?",
                 "<p>Alleen met een laboratoriumanalyse van een monster of via een inventarisatierapport. Beoordelen op het oog is onbetrouwbaar.</p>"),
                ("Mag zeil met asbest gewoon opgerold worden?",
                 "<p>Nee, wanneer het gelijmd is of beschadigd raakt. Alleen los liggend materiaal dat in zijn geheel verwijderd wordt en hechtgebonden is, valt onder de particuliere regeling.</p>"),
                ("Wie betaalt bij een huurwoning?",
                 "<p>De verhuurder, tenzij de huurder de schade zelf heeft veroorzaakt door onoordeelkundig werk.</p>"),
                ("Is een woning van na 1994 asbestvrij?",
                 "<p>In beginsel wel voor toegepast bouwmateriaal. Verbouwingen met oude restpartijen komen incidenteel voor.</p>"),
            ]),
        ],
        _rail("/kennisbank/asbest-in-de-woning/"),
    ))

    # ------------------------------------------------------------ kringloop
    out.append(_p(
        "/kennisbank/hergebruik-en-kringloop/",
        "Hergebruik en kringloop bij een woningontruiming | SpoedWoningOntruiming.nl",
        "Hergebruik en kringloop",
        "Wat kringloopwinkels aannemen en weigeren, hoeveel er landelijk hergebruikt wordt en waar textiel, elektronica en meubels terechtkomen.",
        "Een groot deel van een gemiddelde inboedel is bruikbaar. Wie dat scheidt van het echte afval, verkleint het volume, verlaagt de verwerkingskosten en houdt spullen in omloop.",
        [
            ("h2", "Wat de sector doet"),
            ("p", "De aangesloten kringloopbedrijven van Branchevereniging Kringloop Nederland telden in 2024 62 leden met 242 winkels. Gemiddeld kwam er 747.805 kilo per vestiging binnen. Van alle binnengekomen producten werd 63 procent hergebruikt, tegen 56 procent in 2023. Daarnaast ging 22 procent naar recycling, 14 procent naar restafval en 1 procent naar export. De sector rekent voor dat daarmee 339 miljoen kilo CO2 is bespaard. De winkelomzet bedroeg 155,5 miljoen euro bij 16,7 miljoen betalende klanten."),
            ("h2", "Wat een kringloopwinkel aanneemt"),
            ("table", ["Wel", "Meestal niet"], [
                ["Meubels die heel en schoon zijn", "Bankstellen met vlekken, geuren of beschadigingen"],
                ["Serviesgoed, glaswerk en bestek", "Onvolledige serviezen zonder samenhang"],
                ["Kleding en textiel dat draagbaar is", "Ondergoed, natte of beschimmelde kleding"],
                ["Boeken, platen, cd's en spellen", "Encyclopedieën en tijdschriften"],
                ["Werkende elektrische apparaten", "Apparaten zonder snoer of met bekende defecten"],
                ["Fietsen, gereedschap en tuinmeubilair", "Matrassen, kunststof tuinstoelen, bouwmateriaal"],
            ]),
            ("p", "De meeste kringloopwinkels halen gratis op vanaf een minimale hoeveelheid, met een wachttijd van dagen tot enkele weken. Bij een ontruiming met een korte deadline is dat de beperkende factor, en dan is de afvoerroute via het ontruimingsbedrijf sneller."),
            ("h2", "Waar de rest heen gaat"),
            ("ul", [
                "Textiel: naar sorteercentra voor hergebruik als kleding of als vezel voor nieuwe producten. Er gelden sinds 2025 producentenverplichtingen voor textiel.",
                "Elektronica: naar erkende verwerkers, met een landelijk inzamelsysteem via Stichting OPEN, zie https://www.stichting-open.org.",
                "Hout: naar spaanplaatproductie of naar biomassa, afhankelijk van de kwaliteit.",
                "Metaal: vrijwel volledig recyclebaar en de enige stroom die structureel geld oplevert.",
                "Matrassen: aparte recyclingroute, sinds 2025 met een producentenverantwoordelijkheid.",
                "Restafval: verbranding met energieterugwinning, en de duurste stroom per ton.",
            ]),
            ("note", "Sorteren loont, maar niet oneindig",
             "<p>Bij een ontruiming met een ploeg is uitgebreid sorteren duur, omdat het manuren kost. De grootste winst zit in het vooraf apart zetten van wat werkelijk bruikbaar of waardevol is, en de rest in een keer laten afvoeren.</p>"),
            ("h2", "Doneren aan een goed doel"),
            ("p", "Naast kringloopwinkels nemen kerken, vluchtelingenorganisaties, weggeefwinkels en lokale initiatieven meubels en huisraad aan. Het verschil met een kringloopwinkel is dat zij vaak selectiever zijn en vragen om een foto vooraf. Voor grotere hoeveelheden is een enkel telefoontje naar een lokale organisatie sneller dan een landelijk platform."),
            ("h2", "Veelgestelde vragen"),
            ("faq", [
                ("Betaalt een kringloopwinkel voor een inboedel?",
                 "<p>Zelden. Kringloopwinkels halen bruikbare goederen kosteloos op, maar kopen niet in. Voor verkoop is een opkoper of veilinghuis de route, zie de pagina over <a href=\"/ontruimen/inboedel-opkoop/\">inboedel verkopen</a>.</p>"),
                ("Wordt echt alles hergebruikt wat binnenkomt?",
                 "<p>Nee. In 2024 kwam 63 procent van het binnengekomen materiaal in hergebruik, de rest ging naar recycling of restafval.</p>"),
                ("Nemen kringloopwinkels een hele woninginhoud aan?",
                 "<p>Een deel wel, na beoordeling. Vervuilde of onvolledige inboedels worden geweigerd, omdat sorteren voor hen ook manuren kost.</p>"),
            ]),
        ],
        _rail("/kennisbank/hergebruik-en-kringloop/"),
    ))

    # ------------------------------------------------------------ waardevol
    out.append(_p(
        "/kennisbank/waardevolle-spullen/",
        "Waardevolle spullen herkennen voor een ontruiming | SpoedWoningOntruiming.nl",
        "Waardevolle spullen herkennen",
        "Welke voorwerpen in een gemiddelde woning waarde vertegenwoordigen, waar geld en papieren zich verstoppen en hoe taxatie werkt.",
        "Wat in de container verdwijnt, komt niet terug. Deze pagina behandelt de categorieën die waarde vertegenwoordigen, en de plekken waar in nalatenschappen contant geld en documenten worden aangetroffen.",
        [
            ("h2", "Zes categorieën met waarde"),
            ("table", ["Categorie", "Waar op te letten"], [
                ["Edelmetaal", "Stempels: 585 en 750 voor goud, 833 en 925 voor zilver. Ook in bestek, brillenmonturen, tandwerk en munten."],
                ["Horloges en klokken", "Merknaam op wijzerplaat of kast. Mechanische uurwerken houden waarde, ook niet lopend. Staande klokken en Friese klokken apart laten bekijken."],
                ["Munten en papiergeld", "Nederlandse zilveren guldens en rijksdaalders van voor 1967, buitenlandse verzamelingen in albums, en oude bankbiljetten."],
                ["Design en merkmeubilair", "Labels onder zittingen en aan de onderzijde van tafelbladen. Namen als Artifort, Gispen, Pastoe, Cassina, Thonet, Vitra en Ahrend."],
                ["Kunst en boeken", "Gesigneerde werken, oplagenummers, prenten met een blindstempel. Bij boeken: eerste drukken en gesigneerde exemplaren."],
                ["Gereedschap en instrumenten", "Merkgereedschap, machines, naaimachines, en muziekinstrumenten met een merknaam in de klankkast."],
            ]),
            ("h2", "Waar geld en papieren zich bevinden"),
            ("p", "Bij ontruimingen van nalatenschappen wordt regelmatig contant geld aangetroffen. De plekken zijn opvallend consistent:"),
            ("check", [
                "Tussen bladzijden van boeken en in bijbels.",
                "In enveloppen achter in kledingkasten en onder stapels beddengoed.",
                "In jaszakken van kleding die al jaren hangt.",
                "Achter en onder laden, en in de valse bodem van een kastje.",
                "In koektrommels, vazen, blikken en oude portemonnees.",
                "In de vriezer, in bakjes en verpakkingen.",
                "Achter fotolijsten en spiegels.",
            ]),
            ("p", "Belangrijker dan geld zijn de documenten: polissen, aandelen, spaarbewijzen, testamenten, eigendomsbewijzen, garantiebewijzen en wachtwoordbriefjes. Een polis van een uitvaartverzekering of een levensverzekering die niet wordt gevonden, blijft onbetaald."),
            ("h2", "Digitale zaken"),
            ("p", "Telefoons, laptops, tablets en externe schijven bevatten vaak de enige kopie van foto's en administratie. Zet die apart voordat de woning wordt geruimd. Toegangscodes en wachtwoorden liggen in nalatenschappen vaak op papier bij het apparaat of in een agenda."),
            ("h2", "Taxatie"),
            ("p", "Een taxateur of opkoper beoordeelt op locatie en waardeert per categorie. Voor edelmetaal geldt de dagkoers en het gewicht, voor de rest de verwachte doorverkoopwaarde. Voor een tweede mening bij bijzondere stukken zijn veilinghuizen een route: die geven vaak kosteloos een indicatie op basis van foto's."),
            ("warn", "Bij een nalatenschap eerst de keuze maken",
             "<p>Waardevolle spullen meenemen of verkopen voordat de keuze over de nalatenschap is gemaakt, geldt als zuivere aanvaarding. Fotograferen en laten staan is dan de veilige route, zie de pagina over <a href=\"/kennisbank/erfenis-aanvaarden/\">erfenis aanvaarden of verwerpen</a>.</p>"),
            ("h2", "Veelgestelde vragen"),
            ("faq", [
                ("Kost een taxatie geld?",
                 "<p>Bij een opkoper die ook de ontruiming uitvoert meestal niet. Een onafhankelijk taxateur rekent wel, en dat loont alleen bij een vermoeden van bijzondere stukken.</p>"),
                ("Wat gebeurt er met gevonden geld tijdens een ontruiming?",
                 "<p>Bij een nette ontruimer wordt dat gemeld en apart gelegd. Leg vooraf schriftelijk vast dat gevonden geld, sieraden en documenten worden afgezonderd.</p>"),
                ("Hoe blijkt of een schilderij waarde heeft?",
                 "<p>Signatuur, achterzijde en lijst geven aanwijzingen. Een foto naar een veilinghuis levert vaak binnen een week een indicatie op.</p>"),
            ]),
        ],
        _rail("/kennisbank/waardevolle-spullen/"),
    ))

    # ------------------------------------------------------------ begrippen
    TERMEN = [
        ("Bezemschoon", "Leeg, geveegd en vrij van losse rommel. Geen wettelijke term maar een branchebegrip, en minder ver gaand dan een eindschoonmaak."),
        ("Beneficiair aanvaarden", "Een erfenis aanvaarden onder het voorrecht van boedelbeschrijving, waarbij de erfgenaam niet met eigen vermogen aansprakelijk is voor schulden."),
        ("Beschikkingshandeling", "Een handeling waarmee goederen worden vervreemd of bezwaard, zoals verkopen of weggeven. Leidt bij een nalatenschap tot zuivere aanvaarding."),
        ("Beheershandeling", "Een handeling gericht op instandhouding, zoals opslaan of schoonmaken. Leidt niet tot zuivere aanvaarding."),
        ("Bakwagen", "Vrachtwagen met gesloten laadbak, in deze branche doorgaans met een inhoud van ongeveer twintig kubieke meter."),
        ("Boedelregister", "Register bij de rechtbank waarin verklaringen over aanvaarding en verwerping van nalatenschappen worden opgenomen."),
        ("Casco opleveren", "Een bedrijfsruimte terugbrengen naar de kale bouwkundige staat, zonder door de huurder aangebrachte inrichting."),
        ("Duurzame gemeenschappelijke huishouding", "Samenleven met een bestendig karakter, waardoor een achterblijver na overlijden aanspraak kan maken op voortzetting van de huur."),
        ("Eindinspectie", "De laatste controle van de huurwoning, doorgaans op de dag van de sleuteloverdracht."),
        ("Eindschoonmaak", "Schoonmaak die verder gaat dan bezemschoon: keuken, sanitair, ramen en kasten van binnen."),
        ("Executeur", "In een testament benoemde persoon die bevoegd is de nalatenschap te beheren en af te wikkelen."),
        ("Gevaarlijk afval", "Afval dat vanwege samenstelling apart moet worden ingezameld, zoals verf, accu's, oplosmiddelen en gasflessen."),
        ("Grofvuil", "Huishoudelijk afval dat te groot is voor de container, met per gemeente eigen limieten en tarieven."),
        ("Hechtgebonden asbest", "Asbest waarvan de vezels vastzitten in het dragermateriaal, met een lager risico op vezelverspreiding dan niet-hechtgebonden asbest."),
        ("Hoarding", "Verzamelstoornis waarbij het onvermogen om spullen weg te doen leidt tot ernstige woningvervuiling."),
        ("Inboedel", "Alle roerende zaken in een woning, met uitzondering van zaken die als onroerend worden beschouwd."),
        ("Inboedelopkoop", "Het overnemen van een inboedel tegen betaling of tegen verrekening met de ontruimingskosten."),
        ("Kubieke meter", "De rekeneenheid voor volume bij ontruimingen. Een gemiddeld tweekamerappartement komt uit tussen vijftien en vijfentwintig kubieke meter."),
        ("Kringloop", "Bedrijf of winkel die bruikbare goederen inneemt en opnieuw verkoopt, veelal aangesloten bij de branchevereniging."),
        ("Legitieme portie", "Het deel van de nalatenschap waarop een onterfd kind in geld aanspraak kan maken."),
        ("Medehuurder", "Persoon die naast de huurder als huurder geldt en de huur na diens overlijden voortzet."),
        ("Meerwerk", "Werk buiten de opdrachtomschrijving, dat apart wordt gefactureerd. De belangrijkste bron van discussie achteraf."),
        ("Milieustraat", "Gemeentelijke inzamellocatie voor grofvuil en gescheiden afvalstromen van particuliere huishoudens."),
        ("Nalatenschap", "Het geheel van bezittingen en schulden dat iemand bij overlijden achterlaat."),
        ("Opleverformulier", "Document waarin bij de eindinspectie wordt vastgelegd in welke staat de woning is opgeleverd."),
        ("Opnameformulier", "Beschrijving van de woning bij aanvang van de huur, bepalend voor de opleververplichting."),
        ("ROZ-model", "Standaard huurcontract voor bedrijfsruimte van de Raad voor Onroerende Zaken, met een eigen opleverregime."),
        ("Sanering", "Het verwijderen van verontreiniging, bijvoorbeeld bij een vervuilde woning of bij asbest."),
        ("Sleutelafspraak", "Afspraak waarbij het ontruimingsbedrijf de sleutel ophaalt en de klus uitvoert zonder aanwezigheid van de opdrachtgever."),
        ("Spoedontruiming", "Ontruiming binnen 24 tot 48 uur, doorgaans tegen een opslag van tien tot dertig procent."),
        ("Verklaring van erfrecht", "Notariële akte waarin staat wie de erfgenamen zijn en wie namens hen bevoegd is te handelen."),
        ("Vereffenaar", "Door de rechtbank benoemde persoon die een nalatenschap afwikkelt, bijvoorbeeld wanneer alle erfgenamen hebben verworpen."),
        ("Voorinspectie", "Inspectie enkele weken voor het einde van de huur, waarin de verhuurder vastlegt wat er hersteld moet worden."),
        ("Voorrijkosten", "Kosten voor het aanrijden naar het adres. Bij landelijk werkende ontruimingsbedrijven doorgaans niet in rekening gebracht."),
        ("Wegneemrecht", "Het recht van de huurder om zelf aangebrachte voorzieningen bij vertrek mee te nemen, mits de oude staat wordt hersteld."),
        ("Zelf aangebrachte voorziening", "Verandering of toevoeging die de huurder heeft aangebracht, afgekort tot ZAV."),
        ("Zuivere aanvaarding", "Het volledig aanvaarden van een nalatenschap, inclusief aansprakelijkheid voor schulden met eigen vermogen."),
    ]

    out.append(_p(
        "/kennisbank/begrippenlijst/",
        "Begrippenlijst woningontruiming: 37 termen uitgelegd | SpoedWoningOntruiming.nl",
        "Begrippenlijst",
        "Zevenendertig termen uit offertes, huurcontracten, inspectierapporten en erfrechtelijke stukken, kort en zonder omhaal uitgelegd.",
        "De termen die voorbijkomen in een offerte, een voorinspectierapport of een brief van de notaris, op alfabetische volgorde.",
        [
            ("table", ["Term", "Betekenis"], [[t, u] for t, u in sorted(TERMEN)]),
            ("p", "Een term die ontbreekt kan worden aangedragen via de %s."
             % '<a href="/contact/">contactpagina</a>'),
        ],
        _rail("/kennisbank/begrippenlijst/"),
    ))

    return out
