# -*- coding: utf-8 -*-
from build import dester
from content.shared import ONTRUIM_LINKS, KENNIS_LINKS, hulpbox, contactbox, links_rail

CRUMB = {"/ontruimen/": "Ontruimen"}


def _p(url, title, h1, description, intro, blocks, rail, prio="0.7"):
    return {
        "url": url, "title": title, "h1": h1, "description": description,
        "intro": intro, "blocks": blocks, "rail": rail, "priority": prio,
        "crumb_labels": CRUMB,
    }


def pages():
    out = []

    # ------------------------------------------------------------------ index
    out.append(_p(
        "/ontruimen/",
        "Woningontruiming: soorten ontruimingen en hoe ze verlopen | SpoedWoningOntruiming.nl",
        "Soorten ontruimingen",
        "Overzicht van de negen situaties waarin een woning of pand leeg wordt gehaald, met per situatie de regels, de doorlooptijd en de kostenposten.",
        "Een ontruiming na een overlijden verloopt anders dan een spoedklus voor een makelaar of het leeghalen van een vervuild pand. Hieronder staat per situatie wat er speelt, wie waarvoor verantwoordelijk is en waar de kosten vandaan komen.",
        [
            ("p", "Woningontruiming is een verzamelnaam. In de praktijk gaat het om negen situaties die inhoudelijk sterk verschillen. De inboedel van een zorgkamer past in een bestelbus, een vrijstaand huis met schuur en zolder vraagt meerdere ritten en twee dagen werk. Bij een huurwoning bepaalt de verhuurder wanneer de sleutel binnen moet zijn, bij een koopwoning bepaalt de notaris dat moment."),
            ("p", "De rode draad: bepaal eerst welke situatie van toepassing is, want daaruit volgt de deadline. Uit de deadline volgt of het zelf te doen is of niet, en pas daarna is de prijs een zinnige vraag."),
            ("h2", "De negen situaties"),
            ("cards", [
                ("/ontruimen/spoedontruiming/", "Spoedontruiming",
                 "De woning moet binnen een of twee dagen leeg zijn. Wat er dan realistisch haalbaar is en welke toeslag daarbij hoort."),
                ("/ontruimen/na-overlijden/", "Ontruiming na overlijden",
                 "Wat er eerst geregeld moet zijn, waarom de tweede maand na het overlijden telt en welke handelingen risico geven."),
                ("/ontruimen/seniorenwoning/", "Seniorenwoning ontruimen",
                 "Verhuizing naar een zorginstelling of aanleunwoning, met dubbele huur en een korte opzegtermijn."),
                ("/ontruimen/vervuilde-woning/", "Vervuilde woning ontruimen",
                 "Woningvervuiling en hoarding: beschermingsmiddelen, ongediertebestrijding en herstel van vloeren en wanden."),
                ("/ontruimen/huurwoning-opleveren/", "Huurwoning opleveren",
                 "Voorinspectie, eindinspectie en het verschil tussen bezemschoon en de staat volgens de beschrijving."),
                ("/ontruimen/koopwoning-verkoopklaar/", "Koopwoning verkoopklaar maken",
                 "Leeghalen voor de verkoop of voor de overdracht bij de notaris, inclusief het risico van roerende zaken in de lijst."),
                ("/ontruimen/inboedel-opkoop/", "Inboedel verkopen",
                 "Wanneer een inboedel geld waard is, hoe taxatie werkt en wat er overblijft na aftrek van de afvoerkosten."),
                ("/ontruimen/ontruimen-in-ruil-voor-inboedel/", "Ontruimen in ruil voor de inboedel",
                 "De constructie waarbij de inboedel de rekening dekt, en de voorwaarden waaronder dat werkelijk uitkomt."),
                ("/ontruimen/bedrijfspand/", "Bedrijfspand en winkel",
                 "Kantoor, magazijn of winkel leegruimen, met archiefvernietiging, apparatuur en het herstel naar casco."),
            ], 3),
            ("h2", "Wat elke ontruiming gemeen heeft"),
            ("steps", [
                ("Bepaal de deadline en werk terug",
                 "Bij een huurwoning is dat de datum waarop de sleutel binnen moet zijn, bij een verkoop de dag van de overdracht. Twee werkdagen speling voorkomt dat een tegenvaller meteen een probleem wordt."),
                ("Scheid wat blijft van wat weggaat",
                 "Persoonlijke papieren, sieraden, fotoalbums en apparatuur met gegevens erop eerst apart zetten. Wat eenmaal in de container ligt, komt niet terug."),
                ("Vraag twee of drie offertes op locatie",
                 "Een prijs per telefoon is een gok. Wie de woning heeft gezien, kan een vast bedrag noemen en hoeft achteraf niets bij te tellen."),
                ("Leg de oplevering vast",
                 "Foto's van elke ruimte na afloop, plus het inspectierapport of het ondertekende opleverformulier. Dat is het bewijs bij een latere discussie over schade."),
            ]),
            ("h2", "Wie voert het uit"),
            ("p", "Deze gids voert zelf geen ontruimingen uit en bemiddelt niet. Voor wie een uitvoerende partij zoekt: %s werkt landelijk, rekent geen voorrijkosten en legt de prijs vooraf vast. Een overzicht van de diensten staat op %s."
             % (dester("/", kind="brand"), dester("/", kind="bare"))),
        ],
        [links_rail("Kennisbank", KENNIS_LINKS[:6]),
         ("dark", "Kosten", '<p>Marktbrede prijsbandbreedtes per woningtype staan op de <a href="/kosten/">kostenpagina</a>. Een indicatie voor een concrete situatie geeft de <a href="/tools/kostenindicatie/">kostenindicatie</a>.</p>'),
         contactbox()],
        prio="0.9",
    ))

    # ------------------------------------------------------------ spoed
    out.append(_p(
        "/ontruimen/spoedontruiming/",
        "Spoedontruiming: woning binnen 24 tot 48 uur leeg | SpoedWoningOntruiming.nl",
        "Spoedontruiming",
        "Wat er nodig is om een woning binnen een of twee dagen leeg en bezemschoon te krijgen, welke toeslag daarvoor geldt en wanneer spoed niet lukt.",
        "Spoed betekent in deze branche meestal: melding vandaag, uitvoering morgen of overmorgen. Dat is haalbaar, maar het vraagt drie dingen tegelijk: een ploeg die vrij te maken is, een verwerker die de vracht aanneemt en iemand met de sleutel.",
        [
            ("h2", "Wanneer spoed echt spoed is"),
            ("p", "De meeste spoedaanvragen komen uit vier hoeken. Een verhuurder die de woning per direct terug wil omdat de huur al is opgezegd. Een makelaar die twee dagen voor de overdracht ontdekt dat het pand niet leeg is. Nabestaanden die na een uitvaart merken dat de huurovereenkomst afloopt aan het eind van de tweede maand na het overlijden. En een deurwaarder of gemeente die een gedwongen ontruiming heeft aangezegd."),
            ("p", "In alle vier de gevallen ligt de datum vast en is die niet te verzetten. Dat is het verschil met een gewone ontruiming, waar meestal nog een week te schuiven valt."),
            ("h2", "Wat er in 24 uur haalbaar is"),
            ("p", "Een ploeg van drie tot vier mensen haalt een gemiddeld appartement van twee of drie kamers op een dag leeg, inclusief vloerbedekking en bezemschoon opleveren. Een eengezinswoning met zolder, schuur en tuin loopt richting anderhalf tot twee dagen. Een vrijstaand huis met garage en jaren aan opslag is met 24 uur niet realistisch, hoeveel mensen er ook staan."),
            ("p", "De grens zit zelden in de mankracht en meestal in de afvoer. Een bakwagen neemt ongeveer twintig kubieke meter mee. Een volle eengezinswoning zit al snel op dertig tot vijftig kubieke meter, dus dat zijn twee of drie ritten naar de verwerker, en die is niet zeven dagen per week open."),
            ("warn", "Let op de openingstijden van de verwerker", "<p>Een ontruiming op zondag klinkt aantrekkelijk, maar de meeste afvalverwerkers en milieustraten zijn dan dicht. De vracht blijft dan op de wagen staan tot maandag, wat de planning van de volgende klus raakt. Dat is de reden dat weekendtoeslagen bestaan.</p>"),
            ("h2", "De spoedtoeslag"),
            ("p", "Uitvoering binnen 48 uur kost meer dan uitvoering over twee weken. In de markt ligt die opslag ruwweg tussen tien en dertig procent boven het reguliere tarief, afhankelijk van hoeveel er omgegooid moet worden in de planning. Een klus die op een rustige donderdag past, kost weinig extra. Een klus waarvoor twee andere afspraken verschoven moeten worden, kost het maximum."),
            ("p", "Vergelijk die opslag met wat de vertraging kost. Een maand extra huur van een sociale huurwoning ligt vaak boven de zeshonderd euro, en bij een niet-tijdige oplevering rekenen verhuurders daar doorgaans nog kosten bovenop. Een toeslag van tweehonderd euro om dat te voorkomen is dan snel terugverdiend."),
            ("h2", "Wat de aanvraag versnelt"),
            ("check", [
                "Adres, verdieping, aanwezigheid van een lift en de parkeersituatie voor de deur.",
                "Aantal kamers, plus zolder, kelder, schuur, garage en balkon apart benoemen.",
                "Foto's van elke ruimte, ook de volle kasten en de berging. Een videorondje van twee minuten werkt nog beter.",
                "Wat er blijft staan en wat er meegaat, en of er vloerbedekking of laminaat uit moet.",
                "Wie de sleutel heeft en of die opgehaald mag worden bij makelaar, corporatie of buren.",
                "De harde datum waarop het pand leeg moet zijn, en wie op die datum de sleutel in ontvangst neemt.",
            ]),
            ("p", "Met deze gegevens kan een bedrijf vaak dezelfde dag een vaste prijs afgeven zonder eerst langs te komen. Zonder foto's wordt het een bandbreedte, en die valt uiteindelijk altijd aan de hoge kant uit."),
            ("h2", "Gedwongen ontruiming is iets anders"),
            ("p", "Bij een ontruiming door een deurwaarder na een vonnis gelden andere regels. De deurwaarder bepaalt het tijdstip, de gemeente kan de inboedel voor een periode opslaan en de kosten worden op de bewoner verhaald. Een ontruimingsbedrijf werkt daar in opdracht van de deurwaarder of de verhuurder, niet in opdracht van de bewoner. Wie een ontruimingsvonnis heeft ontvangen, doet er verstandig aan eerst juridisch advies te vragen, bijvoorbeeld bij het Juridisch Loket via https://www.juridischloket.nl."),
            ("h2", "Veelgestelde vragen"),
            ("faq", [
                ("Kan een woning ook in het weekend ontruimd worden?",
                 "<p>Ja, dat bieden veel bedrijven aan, ook in de avond. De vracht kan dan vaak pas op maandag naar de verwerker, dus reken op een toeslag.</p>"),
                ("Moet er iemand aanwezig zijn tijdens een spoedontruiming?",
                 "<p>Niet per se. Veel bedrijven werken op sleutelbasis en leveren foto's van het eindresultaat aan. Bij een woning waar nog waardevolle of persoonlijke spullen uit moeten, is aanwezigheid bij de start wel verstandig.</p>"),
                ("Wat gebeurt er met spullen die per ongeluk zijn meegenomen?",
                 "<p>Een nette ontruimer houdt gevonden documenten, sieraden en sleutels apart en meldt dat. Leg vooraf schriftelijk vast welke categorieën altijd apart gelegd worden.</p>"),
                ("Is een spoedontruiming duurder dan opslag huren?",
                 "<p>Voor een korte periode meestal niet. Opslag betekent twee keer verplaatsen plus maandhuur. Alleen wanneer nog niet vaststaat wat er met de inboedel gebeurt, is tijdelijke opslag een redelijk alternatief.</p>"),
            ]),
            ("partner", "Uitvoering binnen 24 uur",
             "<p>%s ontruimt landelijk en levert bezemschoon op, ook in de avonden en het weekend, met een vaste prijsafspraak vooraf en zonder voorrijkosten. De dienstpagina staat op %s.</p>"
             % (dester("/", kind="brand"), dester("/spoedontruiming/", kind="bare"))),
        ],
        [links_rail("Andere situaties", ONTRUIM_LINKS[1:6]),
         hulpbox("/spoedontruiming/", "spoedontruiming"),
         links_rail("Verder lezen", [("/kosten/", "Wat kost een ontruiming"),
                                     ("/checklists/ontruiming-voorbereiden/", "Checklist voorbereiding"),
                                     ("/tools/inboedelvolume/", "Inboedelvolume berekenen")])],
        prio="0.8",
    ))

    # ------------------------------------------------------------ overlijden
    out.append(_p(
        "/ontruimen/na-overlijden/",
        "Woning ontruimen na overlijden: volgorde, termijnen en risico's | SpoedWoningOntruiming.nl",
        "Ontruiming na overlijden",
        "De volgorde bij het leeghalen van de woning van een overledene: erfenis, huuropzegging, waardevolle spullen en de termijn van twee maanden.",
        "Het leeghalen van de woning van een overledene is deels een praktische klus en deels een juridische. Wie de volgorde omdraait, loopt het risico persoonlijk aansprakelijk te worden voor schulden uit de nalatenschap.",
        [
            ("h2", "Eerst de erfenis, dan de spullen"),
            ("p", "De belangrijkste regel staat in artikel 4:192 van het Burgerlijk Wetboek. Een erfgenaam aanvaardt de nalatenschap zuiver zodra hij zich ondubbelzinnig gedraagt als iemand die zuiver aanvaard heeft, bijvoorbeeld door goederen te verkopen, weg te geven of anderszins aan schuldeisers te onttrekken. Zuiver aanvaarden betekent dat eventuele schulden uit de nalatenschap ook uit het eigen vermogen betaald moeten worden."),
            ("p", "Sinds de Wet bescherming erfgenamen tegen schulden uit 2016 is dat criterium versmald. Normale beheershandelingen tellen niet mee. Het leeghalen van de woning, het opslaan van de inboedel en het afvoeren van spullen zonder werkelijke economische waarde gelden als beheer, niet als beschikken. Rechtspraak bevestigt dat het opslaan van inboedelgoederen een daad van beheer is."),
            ("warn", "De grens ligt bij waarde", "<p>Een kast naar de kringloop brengen is beheer. De sieraden verdelen onder de kleinkinderen, de auto verkopen of het horloge meenemen is beschikken, en dat leidt tot zuivere aanvaarding. Bij twijfel over de schulden: eerst beneficiair aanvaarden bij de rechtbank, dan pas ruimen.</p>"),
            ("h2", "De huurovereenkomst loopt korter door dan gedacht"),
            ("p", "Woonde de overledene alleen en is er geen medehuurder of achterblijver met een duurzame gemeenschappelijke huishouding, dan eindigt de huurovereenkomst van rechtswege aan het eind van de tweede maand na het overlijden. Dat volgt uit artikel 7:268 lid 6 van het Burgerlijk Wetboek. De erfgenamen mogen de huur bovendien laten eindigen tegen het eind van de eerste maand na het overlijden."),
            ("p", "Praktisch betekent dat: bij een overlijden op 12 maart loopt de huur zonder opzegging door tot en met 31 mei, en met opzegging tot en met 30 april. In beide gevallen moet de woning op die datum leeg en volgens de eisen opgeleverd zijn. Wachten tot de laatste week is de meest gemaakte fout, omdat een ontruiming inclusief afvoer en schoonmaak minstens een paar dagen planning kost."),
            ("h2", "Volgorde die werkt"),
            ("steps", [
                ("Overlijdensakte en testamentcheck",
                 "De gemeente van overlijden geeft de akte af. Via het Centraal Testamentenregister, https://www.centraaltestamentenregister.nl, blijkt of er een testament is en bij welke notaris."),
                ("Keuze over de nalatenschap",
                 "Zuiver aanvaarden, beneficiair aanvaarden of verwerpen. Beneficiair aanvaarden gebeurt met een verklaring bij de rechtbank en beschermt tegen onbekende schulden."),
                ("Huur opzeggen of laten aflopen",
                 "Schriftelijk melden bij de verhuurder, met de overlijdensakte erbij. Meteen vragen naar de voorinspectie en het opleverformulier."),
                ("Persoonlijke zaken veiligstellen",
                 "Administratie, sieraden, fotoalbums, laptops en telefoons apart zetten, voordat er iemand anders in de woning komt."),
                ("Waarde bepalen wat waarde heeft",
                 "Antiek, klokken, sieraden, gereedschap en verzamelingen laten taxeren voordat de rest wordt afgevoerd."),
                ("Ontruimen en opleveren",
                 "Offertes op locatie, ontruiming, schoonmaak en foto's van het eindresultaat. Sleutel pas afgeven na een ondertekend opleverformulier."),
            ]),
            ("h2", "Wat er vaak over het hoofd wordt gezien"),
            ("ul", [
                "Post laten doorsturen voordat de brievenbus onbewaakt is, via de verhuisservice van PostNL op https://www.postnl.nl.",
                "Digitale toegang: telefoons, laptops en cloudaccounts bevatten vaak de enige kopie van foto's en administratie.",
                "Abonnementen en energiecontracten, want die lopen door tot ze opgezegd zijn.",
                "Sleutels van bergingen, garageboxen en fietsenstallingen die niet in de woning liggen.",
                "Huurderszaken zoals een geplaatste keuken of schuur, die volgens het contract terug moeten naar de oude staat.",
            ]),
            ("h2", "Kosten van de nalatenschap"),
            ("p", "De ontruimingskosten zijn een schuld van de nalatenschap, net als de uitvaartkosten. Is er voldoende saldo, dan worden ze daaruit betaald. Is de nalatenschap negatief en hebben de erfgenamen beneficiair aanvaard of verworpen, dan kunnen de kosten niet zomaar op hen verhaald worden. Verhuurders zetten in dat geval vaak zelf de ontruiming in gang en verhalen wat te verhalen valt op de boedel."),
            ("h2", "Veelgestelde vragen"),
            ("faq", [
                ("Mag de woning al leeggehaald worden voordat de erfenis is aanvaard?",
                 "<p>Ja, mits het bij beheer blijft. Ruimen, opslaan en afvoeren van spullen zonder economische waarde is toegestaan. Verkopen of verdelen van waardevolle zaken niet, dat geldt als zuiver aanvaarden.</p>"),
                ("Hoe lang blijft de huur doorlopen?",
                 "<p>Zonder medehuurder eindigt de huur aan het eind van de tweede maand na het overlijden. Erfgenamen kunnen die termijn verkorten tot het eind van de eerste maand.</p>"),
                ("Wie betaalt als de erfgenamen de erfenis verwerpen?",
                 "<p>Dan is er niemand die de woning hoeft leeg te halen. De verhuurder ruimt en verhaalt de kosten op de nalatenschap. Blijft daar niets van over, dan draagt de verhuurder de kosten.</p>"),
                ("Kan de ontruiming zonder aanwezigheid van familie?",
                 "<p>Ja. Veel bedrijven werken op sleutelbasis en leveren foto's van de lege woning. Vooraf schriftelijk vastleggen welke categorieën spullen apart gelegd worden, is dan wel belangrijk.</p>"),
                ("Wat gebeurt er met de inboedel?",
                 "<p>Bruikbare spullen gaan doorgaans naar kringloop of hergebruik, de rest wordt gescheiden aangeboden bij een verwerker. Bij een inboedel met waarde kan een deel worden opgekocht en verrekend met de rekening.</p>"),
            ]),
            ("partner", "Ontruiming na overlijden",
             "<p>%s werkt bij ontruimingen na overlijden met sleutelafspraken, houdt gevonden documenten en waardevolle zaken apart en levert bezemschoon op volgens de eisen van de corporatie. De dienstpagina staat op %s, de variant waarbij het huis volledig wordt leeggehaald op %s.</p>"
             % (dester("/", kind="brand"), dester("/woning-na-overlijden/", kind="bare"),
                dester("/huis-leeghalen-na-overlijden/", kind="bare"))),
        ],
        [links_rail("Kennisbank", [("/kennisbank/erfenis-aanvaarden/", "Erfenis aanvaarden of verwerpen"),
                                   ("/kennisbank/huur-opzeggen-na-overlijden/", "Huur opzeggen na overlijden"),
                                   ("/kennisbank/verklaring-van-erfrecht/", "Verklaring van erfrecht"),
                                   ("/kennisbank/waardevolle-spullen/", "Waardevolle spullen herkennen")]),
         hulpbox("/woning-na-overlijden/", "ontruiming na overlijden"),
         links_rail("Praktisch", [("/checklists/na-overlijden/", "Checklist na overlijden"),
                                  ("/kosten/", "Kosten en bandbreedtes")])],
        prio="0.8",
    ))

    # ------------------------------------------------------------ senioren
    out.append(_p(
        "/ontruimen/seniorenwoning/",
        "Seniorenwoning ontruimen bij verhuizing naar een zorginstelling | SpoedWoningOntruiming.nl",
        "Seniorenwoning ontruimen",
        "Wat er komt kijken bij het leeghalen van een seniorenwoning: dubbele huur, korte opzegtermijn, meeverhuizende spullen en de rol van familie.",
        "Bij een verhuizing naar een verpleeghuis of aanleunwoning gaat het zelden om een geplande verhuizing. Vaak volgt de opname op een val of een ziekenhuisopname, en moet de oude woning binnen enkele weken leeg zijn terwijl de bewoner er nog niet aan toe is.",
        [
            ("h2", "Twee huren tegelijk"),
            ("p", "De opnamedatum in de zorginstelling en de einddatum van de huurovereenkomst vallen zelden samen. Bij sociale huur geldt doorgaans een opzegtermijn van een maand, gerekend vanaf de dag van opzegging. Dat betekent in de praktijk een periode waarin zowel de eigen bijdrage voor de zorginstelling als de huur van de oude woning betaald wordt. Die periode zo kort mogelijk houden is meestal de grootste besparing van het hele traject."),
            ("p", "Bij een koopwoning speelt het omgekeerde: de woning moet leeg en verkoopklaar zijn, terwijl de opbrengst pas na de overdracht binnenkomt. De vermogenstoets voor de eigen bijdrage aan de Wet langdurige zorg maakt het bovendien verstandig om het traject vooraf met een financieel adviseur of het CAK door te nemen. Informatie daarover staat op https://www.hetcak.nl."),
            ("h2", "Wat er mee kan naar de nieuwe kamer"),
            ("p", "Een kamer in een verpleeghuis meet vaak tussen de achttien en vijfentwintig vierkante meter, inclusief eigen sanitair. Daar past een fauteuil, een kast, een tv, een nachtkastje en een handvol persoonlijke spullen. Het bed komt meestal van de instelling, omdat het hoog-laag verstelbaar moet zijn."),
            ("check", [
                "Meet de nieuwe kamer op en teken de indeling voordat er iets wordt ingepakt.",
                "Vraag de instelling wat er standaard aanwezig is, en of eigen meubels brandveiligheidseisen moeten halen.",
                "Kies vijf tot tien voorwerpen met emotionele waarde die zeker meegaan, en fotografeer de rest voor een fotoboek.",
                "Regel een adreswijziging bij gemeente, bank, zorgverzekeraar en pensioenfonds.",
                "Controleer of het huurcontract een schuur, berging of parkeerplaats omvat die apart opgezegd moet worden.",
            ]),
            ("h2", "Familie en emotie"),
            ("p", "Een seniorenwoning bevat vaak zestig jaar aan bezit. Het verschil tussen een ontruiming die goed voelt en een die pijnlijk blijft, zit meestal in het tempo. Wanneer familie samen een dag neemt om te kiezen wat blijft, en het ruimen daarna aan een bedrijf wordt overgelaten, blijft de emotionele kant gescheiden van het zware werk."),
            ("p", "Waar meerdere kinderen betrokken zijn, helpt het om de verdeling schriftelijk vast te leggen voordat er iets uit de woning verdwijnt. Het gaat zelden om de waarde en bijna altijd om het gevoel dat iemand iets is misgelopen."),
            ("h2", "De woning zelf"),
            ("p", "Seniorenwoningen bevatten vaak aanpassingen die via de Wmo zijn geplaatst: een traplift, beugels, een verhoogd toilet of een drempelhulp. Wie die aanpassingen heeft betaald, bepaalt of ze blijven zitten of verwijderd moeten worden. Bij een gemeentelijke verstrekking haalt de leverancier de voorziening doorgaans zelf op, en dat kost tijd die in de planning moet."),
            ("p", "Verder geldt het gewone opleverregime: vloerbedekking eruit als de verhuurder dat eist, schroeven en pluggen uit de muur, gaten dichten en bezemschoon opleveren. Wat daar precies onder valt, staat op de pagina over %s."
             % '<a href="/ontruimen/huurwoning-opleveren/">het opleveren van een huurwoning</a>'),
            ("h2", "Volgorde in de tijd"),
            ("table", ["Moment", "Actie"], [
                ["Week 1", "Opnamedatum bekend, huur opzeggen, voorinspectie aanvragen bij de verhuurder"],
                ["Week 1 tot 2", "Kamer opmeten, meeverhuizende spullen kiezen, adreswijzigingen doorgeven"],
                ["Week 2", "Familie kiest persoonlijke zaken, taxatie van eventueel waardevolle spullen"],
                ["Week 2 tot 3", "Offertes op locatie, datum ontruiming vastleggen, Wmo-voorzieningen laten ophalen"],
                ["Week 3 tot 4", "Ontruiming, herstelwerk, schoonmaak, eindinspectie en sleuteloverdracht"],
            ]),
            ("h2", "Veelgestelde vragen"),
            ("faq", [
                ("Wie mag de huur opzeggen als de bewoner dat zelf niet meer kan?",
                 "<p>Een gemachtigde op basis van een volmacht, of een bewindvoerder of curator wanneer die is benoemd. Zonder een van beide vraagt de verhuurder doorgaans om een verklaring van de instelling.</p>"),
                ("Kan een deel van de inboedel opgeslagen worden?",
                 "<p>Ja, maar reken op maandkosten plus twee verplaatsingen. Alleen zinvol wanneer nog niet vaststaat wat er met de spullen gebeurt.</p>"),
                ("Moet de vloerbedekking eruit?",
                 "<p>Dat hangt af van het huurcontract en de voorinspectie. Sommige corporaties nemen een nette vloer over voor de volgende huurder, andere eisen een kale ondervloer.</p>"),
                ("Wat gebeurt er met de traplift?",
                 "<p>Bij een Wmo-verstrekking haalt de leverancier hem terug. Bij een zelf gekochte lift is verwijdering en herstel van de trap voor rekening van de bewoner of de erfgenamen.</p>"),
            ]),
            ("partner", "Seniorenwoning ontruimen",
             "<p>%s heeft een aparte werkwijze voor seniorenwoningen, met ruimte voor familie om eerst te kiezen wat blijft. De dienstpagina staat op %s.</p>"
             % (dester("/", kind="brand"), dester("/seniorenwoning-ontruimen/", kind="bare"))),
        ],
        [links_rail("Andere situaties", [ONTRUIM_LINKS[1], ONTRUIM_LINKS[4], ONTRUIM_LINKS[6]]),
         hulpbox("/seniorenwoning-ontruimen/", "seniorenwoning ontruimen"),
         links_rail("Praktisch", [("/checklists/verhuizing-naar-zorginstelling/", "Checklist verhuizing naar zorg"),
                                  ("/tools/kostenindicatie/", "Kostenindicatie")])],
    ))

    # ------------------------------------------------------------ vervuild
    out.append(_p(
        "/ontruimen/vervuilde-woning/",
        "Vervuilde woning ontruimen: hoarding, ongedierte en herstel | SpoedWoningOntruiming.nl",
        "Vervuilde woning ontruimen",
        "Werkwijze bij ernstige woningvervuiling en hoarding: beschermingsmiddelen, ongediertebestrijding, geurbehandeling en herstel van vloeren en wanden.",
        "Ernstige woningvervuiling is geen schoonmaakklus met een grotere emmer. Het is gespecialiseerd werk waarbij gezondheidsrisico's, ongedierte en bouwkundige schade samenkomen, en waarbij de bewoner vrijwel altijd hulp nodig heeft die verder gaat dan het leeghalen zelf.",
        [
            ("h2", "Hoe vaak het voorkomt"),
            ("p", "Meldingen van hoarding en woningvervuiling nemen toe. Rotterdam ging van ongeveer tweehonderd meldingen per jaar voor de coronaperiode naar driehonderdvijftig, Amsterdam telt jaarlijks rond de driehonderdvijftig ernstig vervuilde woningen. Uit een uitvraag van GGD GHOR blijkt landelijk een stijging tussen zestig en honderdvijftig procent, afhankelijk van gemeente en regio. De Amsterdamse ombudsman legde in het rapport Als de zorgen boven het hoofd groeien de link met toenemende eenzaamheid, ambulantisering en bezuinigingen in de zorg."),
            ("h2", "Drie gradaties"),
            ("table", ["Gradatie", "Beeld", "Aanpak"], [
                ["Lichte vervuiling", "Volle woning, achterstallige schoonmaak, geen ongedierte, vloeren intact",
                 "Reguliere ontruiming plus een grondige eindschoonmaak"],
                ["Ernstige vervuiling", "Looppaden tussen stapels, etensresten, ongedierte, vlekken in vloer en wand",
                 "Beschermingsmiddelen, gescheiden afvoer, ongediertebestrijding, vloeren eruit"],
                ["Extreme vervuiling", "Uitwerpselen, schimmel op wanden, aangetast houtwerk, sterke geur",
                 "Sanering, geurbehandeling met ozon, vervangen van vloerdelen, plafonds en soms leidingwerk"],
            ]),
            ("h2", "Werkwijze"),
            ("steps", [
                ("Opname met beschermingsmiddelen",
                 "Een eerste bezoek met handschoenen, overall en ademmasker om de gradatie te bepalen. Foto's zijn hierbij belangrijker dan bij een gewone opname, omdat de omvang pas zichtbaar wordt als de eerste laag weg is."),
                ("Ongedierte eerst",
                 "Bij aanwezigheid van ratten, muizen, kakkerlakken of vlooien komt de bestrijder voor of gelijktijdig met de ontruiming. Ruimen zonder bestrijding verplaatst het probleem naar de buren."),
                ("Gescheiden afvoer",
                 "Restafval, grofvuil, elektronica, chemisch afval en soms medisch afval gaan naar verschillende stromen. Dat verklaart een deel van het prijsverschil met een gewone ontruiming."),
                ("Reiniging en geurbehandeling",
                 "Na het leeghalen volgt reiniging van wanden, plafonds en sanitair. Bij hardnekkige geur wordt de woning behandeld met ozon of een vergelijkbare methode, waarna hij enkele uren gesloten blijft."),
                ("Herstel",
                 "Vloerbedekking, laminaat en soms de onderliggende vloerdelen gaan eruit. Aangetast stucwerk wordt verwijderd, wanden worden gesausd en gaten hersteld."),
            ]),
            ("warn", "De bewoner is het eigenlijke onderwerp",
             "<p>Hoarding is in de meeste gevallen een uiting van een onderliggend probleem. Ruimen zonder begeleiding leidt er regelmatig toe dat de woning binnen een jaar opnieuw vol staat. De GGD, het wijkteam en het Leger des Heils bieden hulp, zie https://www.legerdesheils.nl/hoarding. Corporaties koppelen een ontruiming daarom steeds vaker aan een zorgtraject.</p>"),
            ("h2", "Wat het kost en waarom"),
            ("p", "Een vervuilde woning kost een veelvoud van een gewone ontruiming van dezelfde omvang. In de markt lopen de bedragen voor zwaar vervuilde panden op vanaf ongeveer tweeduizendvijfhonderd euro tot zesduizend euro en hoger. Het verschil zit in vier dingen: meer manuren per kubieke meter, beschermingsmiddelen die na afloop worden weggegooid, duurdere afvalstromen en herstelwerk dat bij een gewone ontruiming niet nodig is."),
            ("p", "Verzekeringen dekken dit zelden. Een inboedel- of opstalverzekering keert uit bij een plotselinge gebeurtenis, niet bij geleidelijke vervuiling. Bij schade aan het gehuurde stelt de verhuurder de huurder aansprakelijk, of de nalatenschap wanneer de bewoner is overleden."),
            ("h2", "Veelgestelde vragen"),
            ("faq", [
                ("Kan een vervuilde woning in een dag leeg?",
                 "<p>Zelden. Ernstige vervuiling vraagt twee tot vijf dagen, inclusief bestrijding, reiniging en herstel. De ontruiming zelf is vaak het kortste onderdeel.</p>"),
                ("Wie betaalt bij een huurwoning?",
                 "<p>In beginsel de huurder, of de nalatenschap na een overlijden. Corporaties schieten de kosten regelmatig voor en verhalen die daarna. Bij een zorgtraject dragen gemeente en corporatie soms samen bij.</p>"),
                ("Wordt er nog iets bewaard?",
                 "<p>Ja. Documenten, sieraden, geld en persoonlijke papieren worden apart gelegd. In vervuilde woningen wordt regelmatig contant geld tussen papierstapels aangetroffen.</p>"),
                ("Blijft de geur weg?",
                 "<p>Na sanering, verwijdering van poreuze materialen en een geurbehandeling meestal wel. Blijft de geur terugkomen, dan zit hij vaak in de ondervloer of in het leidingwerk.</p>"),
            ]),
            ("partner", "Vervuilde woning ontruimen",
             "<p>%s ontruimt vervuilde woningen inclusief bestrijding, reiniging en herstel. De dienstpagina staat op %s. De combinatie van ontruiming en schoonmaak staat beschreven op %s.</p>"
             % (dester("/", kind="brand"), dester("/vervuilde-woning-ontruimen/", kind="bare"),
                dester("/ontruimen-en-schoonmaken/", kind="bare"))),
        ],
        [links_rail("Andere situaties", [ONTRUIM_LINKS[0], ONTRUIM_LINKS[1], ONTRUIM_LINKS[4]]),
         hulpbox("/vervuilde-woning-ontruimen/", "vervuilde woning ontruimen"),
         links_rail("Kennisbank", [("/kennisbank/asbest-in-de-woning/", "Asbest in de woning"),
                                   ("/kennisbank/grofvuil-en-milieustraat/", "Grofvuil en milieustraat")])],
    ))

    # ------------------------------------------------------------ huurwoning opleveren
    out.append(_p(
        "/ontruimen/huurwoning-opleveren/",
        "Huurwoning opleveren: voorinspectie, eindinspectie en bezemschoon | SpoedWoningOntruiming.nl",
        "Huurwoning opleveren",
        "Hoe de oplevering van een huurwoning juridisch in elkaar zit, wat bezemschoon betekent en waar discussies met de verhuurder over gaan.",
        "De oplevering bepaalt of er achteraf een rekening volgt. Twee wetsartikelen en twee inspecties beslissen wie waarvoor opdraait, en beide zijn eenvoudiger dan ze klinken.",
        [
            ("h2", "Wat de wet zegt"),
            ("p", "Artikel 7:224 lid 1 van het Burgerlijk Wetboek bepaalt dat de huurder het gehuurde bij het einde van de huur weer ter beschikking stelt van de verhuurder. Lid 2 regelt de staat waarin dat gebeurt. Is er bij aanvang een beschrijving van de woning opgemaakt, dan moet de woning in die staat terug, met uitzondering van toegestane veranderingen en van wat door ouderdom is versleten of beschadigd."),
            ("p", "Ontbreekt zo'n beschrijving, dan geldt een wettelijk vermoeden in het voordeel van de huurder: de woning wordt verondersteld te zijn ontvangen in de staat waarin hij zich bij het einde van de huur bevindt. De verhuurder mag tegenbewijs leveren, bijvoorbeeld met foto's uit de begintijd, maar de bewijslast ligt bij hem."),
            ("note", "Zoek het opnameformulier op",
             "<p>Het formulier uit de begintijd van de huur, vaak met foto's of een omschrijving per ruimte, is het belangrijkste document van de hele oplevering. Zonder dat document staat de huurder juridisch sterker dan met een slecht ingevuld exemplaar.</p>"),
            ("h2", "Voorinspectie en eindinspectie"),
            ("p", "De voorinspectie vindt enkele weken voor het einde van de huur plaats. De verhuurder loopt de woning door en legt vast wat er nog hersteld moet worden. Dat rapport is de opdrachtlijst voor de ontruiming: wat er niet in staat, kan later moeilijk geëist worden."),
            ("p", "Voert de verhuurder geen voorinspectie uit, dan is zijn positie zwakker. Hij kan dan in beginsel alleen de kosten vorderen die de huurder zelf gemaakt zou hebben om het gebrek te herstellen, dus materiaalkosten en niet het uurtarief van een aannemer. Dat scheelt in de praktijk fors."),
            ("p", "De eindinspectie is de sleuteloverdracht. Daar wordt vastgesteld of de punten uit de voorinspectie zijn afgehandeld. Een ondertekend formulier waarin staat dat de woning akkoord is opgeleverd, sluit latere claims in de meeste gevallen af."),
            ("h2", "Wat bezemschoon betekent"),
            ("p", "Bezemschoon is geen wettelijke term maar een branchebegrip. In de praktijk betekent het: leeg, geveegd, geen losse rommel, geen stof- of etensresten, sanitair en keuken zonder aanslag, en alle ruimtes toegankelijk. Het betekent niet: ramen gelapt, kozijnen gesopt of de oven ontvet. Wie een woning aan een makelaar of nieuwe huurder oplevert, kiest vaker voor een eindschoonmaak die verder gaat."),
            ("table", ["Onderdeel", "Bezemschoon", "Eindschoonmaak"], [
                ["Vloeren", "Geveegd, vrij van rommel", "Gedweild en ontvet"],
                ["Keuken", "Kasten leeg, oppervlakken geveegd", "Kasten van binnen gereinigd, oven en afzuigkap ontvet"],
                ["Sanitair", "Leeg en zichtbaar schoon", "Ontkalkt, voegen behandeld, spiegels gelapt"],
                ["Ramen", "Niet inbegrepen", "Binnenzijde gelapt, kozijnen afgenomen"],
                ["Berging en balkon", "Leeg en geveegd", "Leeg, geveegd en geschrobd"],
            ]),
            ("h2", "Waar de discussie meestal over gaat"),
            ("ul", [
                "Vloerbedekking en laminaat: sommige verhuurders eisen een kale ondervloer, andere nemen een nette vloer over voor de volgende huurder. Dit staat in het voorinspectierapport.",
                "Schroeven, pluggen en boorgaten: het standaardpunt bij vrijwel elke eindinspectie. Gaten dichten en overschilderen kost weinig en voorkomt een post van honderd euro of meer.",
                "Muurkleuren: veel contracten eisen een neutrale kleur bij oplevering. Een donkere wand vraagt twee lagen dekkende verf.",
                "Zelf geplaatste keukens, schuurtjes en zonwering: die vallen onder de zelf aangebrachte voorzieningen, zie de pagina over " + '<a href="/kennisbank/zelf-aangebrachte-voorzieningen/">zelf aangebrachte voorzieningen</a>.',
                "Tuin: bij een eengezinswoning hoort een onderhouden tuin bij de oplevering. Een verwilderde tuin leidt regelmatig tot een aparte rekening.",
            ]),
            ("h2", "Volgorde die problemen voorkomt"),
            ("steps", [
                ("Voorinspectie aanvragen zodra de huur is opgezegd",
                 "Wachten tot de verhuurder zelf belt, kost dagen die later nodig zijn."),
                ("Het rapport punt voor punt aflopen",
                 "Wat onduidelijk is, meteen navragen en het antwoord per e-mail laten bevestigen."),
                ("Ontruimen, dan herstellen, dan schoonmaken",
                 "In die volgorde. Herstelwerk in een volle woning kost twee keer zo veel tijd."),
                ("Foto's maken van elke ruimte na afloop",
                 "Met datum. Dit is het bewijs bij een discussie over schade die later wordt gemeld."),
                ("Sleutel pas afgeven na ondertekening",
                 "Het ondertekende eindformulier is het sluitstuk. Zonder dat document blijft de zaak open."),
            ]),
            ("h2", "Veelgestelde vragen"),
            ("faq", [
                ("Mag de verhuurder kosten in rekening brengen zonder voorinspectie?",
                 "<p>Slechts beperkt. Zonder voorinspectie kan hij in beginsel alleen vorderen wat de huurder zelf aan herstel zou hebben uitgegeven, dus geen arbeidsloon van een aannemer.</p>"),
                ("Wat als er geen beschrijving bij aanvang is opgemaakt?",
                 "<p>Dan wordt de huurder vermoed de woning te hebben ontvangen in de staat waarin hij hem achterlaat. De verhuurder moet dan bewijzen dat de staat bij aanvang beter was.</p>"),
                ("Telt normale slijtage mee?",
                 "<p>Nee. Wat door ouderdom is versleten of beschadigd, valt buiten de opleververplichting.</p>"),
                ("Moet de woning geschilderd worden opgeleverd?",
                 "<p>Alleen wanneer het contract of het voorinspectierapport dat eist, bijvoorbeeld bij afwijkende kleuren. Standaard slijtage van verf hoeft niet hersteld te worden.</p>"),
            ]),
            ("partner", "Oplevering inclusief herstel",
             "<p>%s levert op conform de eisen van de woningcorporatie of makelaar, inclusief het verwijderen van vloeren, dichten van gaten en de eindschoonmaak. Uitleg over bezemschoon opleveren staat op %s.</p>"
             % (dester("/", kind="brand"), dester("/bezemschoon-opleveren/", kind="bare"))),
        ],
        [links_rail("Kennisbank", [("/kennisbank/oplevering-en-beschrijving/", "Oplevering en beschrijving"),
                                   ("/kennisbank/zelf-aangebrachte-voorzieningen/", "Zelf aangebrachte voorzieningen"),
                                   ("/kennisbank/huur-opzeggen-na-overlijden/", "Huur opzeggen na overlijden")]),
         hulpbox("/bezemschoon-opleveren/", "bezemschoon opleveren"),
         links_rail("Praktisch", [("/checklists/oplevering-huurwoning/", "Checklist oplevering"),
                                  ("/kosten/", "Kosten en bandbreedtes")])],
        prio="0.8",
    ))

    # ------------------------------------------------------------ koopwoning
    out.append(_p(
        "/ontruimen/koopwoning-verkoopklaar/",
        "Koopwoning leeghalen en verkoopklaar maken | SpoedWoningOntruiming.nl",
        "Koopwoning verkoopklaar maken",
        "Leeghalen voor de verkoop of voor de overdracht: de lijst van zaken, het verschil tussen leeg en bezemschoon, en de planning rond de notaris.",
        "Bij een koopwoning is er geen verhuurder die eisen stelt, maar wel een koopakte en een notaris. Wat er achterblijft en in welke staat, staat in de lijst van zaken en in de akte. Die twee documenten bepalen de klus.",
        [
            ("h2", "De lijst van zaken is bindend"),
            ("p", "In de koopovereenkomst hoort een lijst van zaken waarop per onderdeel staat of het achterblijft, meegaat of ter overname is. Gordijnen, lampen, tuinhuis, zonwering en keukenapparatuur staan daar doorgaans in. Wat als achterblijvend is aangekruist, moet er bij de overdracht ook werkelijk zijn. Wat meegaat, moet weg zijn."),
            ("p", "De praktische fout is het weghalen van iets dat volgens de lijst blijft, bijvoorbeeld een vaste kast of een vloer. De koper kan dan herstel of vergoeding eisen, en dat wordt bij de notaris nog voor de sleuteloverdracht rechtgezet."),
            ("h2", "Leeg, bezemschoon of gestyled"),
            ("p", "Er zijn drie momenten waarop een koopwoning geruimd wordt, en ze vragen elk iets anders."),
            ("table", ["Moment", "Doel", "Wat er nodig is"], [
                ["Voor de bezichtigingen", "Beter verkopen",
                 "Ruimte maken, persoonlijke spullen weg, kasten leeg, foto's laten maken in een rustige woning"],
                ["Voor de overdracht", "Voldoen aan de akte",
                 "Leeg volgens de lijst van zaken, bezemschoon, alle sleutels compleet, meterstanden genoteerd"],
                ["Na de overdracht", "Alleen bij afspraak",
                 "Uitsluitend wanneer de koper schriftelijk toestemming geeft; anders is de woning niet conform geleverd"],
            ]),
            ("h2", "Woning uit een nalatenschap"),
            ("p", "Een koopwoning uit een erfenis vraagt eerst een verklaring van erfrecht, want zonder dat document kan de notaris de eigendom niet overdragen. Kosten daarvan liggen in 2026 doorgaans vanaf ongeveer vierhonderd euro, afhankelijk van het aantal erfgenamen en de complexiteit. Meer daarover staat op de pagina over %s."
             % '<a href="/kennisbank/verklaring-van-erfrecht/">de verklaring van erfrecht</a>'),
            ("p", "Zolang de woning niet verkocht is, lopen de vaste lasten door: hypotheekrente of opstalverzekering, gemeentelijke heffingen, energie en soms servicekosten. Dat is de reden dat het leeghalen zelden loont om uit te stellen, ook wanneer de emotionele kant om tijd vraagt."),
            ("h2", "Wat kopers en makelaars opmerken"),
            ("ul", [
                "Een lege woning oogt kleiner dan een gemeubileerde, maar laat gebreken zien die anders verborgen blijven. Herstel eerst de opvallende dingen: gaten, losse plinten, kapotte lichtpunten.",
                "Vloerbedekking uit de jaren tachtig kost meer aan onderhandelingsruimte dan aan verwijdering.",
                "Een volle zolder of schuur maakt een woning onverkoopbaarder dan de staat van de keuken.",
                "De tuin is bij bezichtigingen het eerste en het laatste beeld.",
            ]),
            ("h2", "Planning rond de overdracht"),
            ("steps", [
                ("Twee weken voor de overdracht: laatste ronde",
                 "Bepaal wat mee moet, wat achterblijft volgens de lijst en wat afgevoerd wordt."),
                ("Een week voor de overdracht: ontruimen",
                 "Zo blijft er ruimte voor herstel en schoonmaak, en voor tegenvallers zoals een tweede afvoerrit."),
                ("Twee dagen voor de overdracht: eindschoonmaak",
                 "Inclusief ramen, keuken en sanitair. Kopers letten hier meer op dan verhuurders."),
                ("De ochtend van de overdracht: inspectie met de koper",
                 "Meterstanden noteren, alle sleutels tellen, en pas daarna naar de notaris."),
            ]),
            ("h2", "Veelgestelde vragen"),
            ("faq", [
                ("Moet een koopwoning bezemschoon worden opgeleverd?",
                 "<p>Dat staat in de koopakte. In de standaardakte is bezemschoon en ontruimd de norm, tenzij anders is afgesproken.</p>"),
                ("Mag de verkoper spullen achterlaten voor de koper?",
                 "<p>Alleen met schriftelijke instemming. Zonder afspraak zijn achtergelaten spullen een gebrek in de levering en kan de koper afvoerkosten verhalen.</p>"),
                ("Wat gebeurt er als de woning op de dag van overdracht niet leeg is?",
                 "<p>De notaris kan een deel van de koopsom in depot houden of de overdracht uitstellen. Beide leveren kosten en discussie op.</p>"),
                ("Loont het om een woning gestyled te verkopen?",
                 "<p>Bij een woning uit een nalatenschap gaat het vaak vooral om ruimen en herstellen. Volledige styling is een aparte dienst en weegt niet in elke markt op tegen de kosten.</p>"),
            ]),
            ("partner", "Leeghalen voor verkoop of overdracht",
             "<p>%s haalt woningen leeg voor makelaars en particuliere verkopers, inclusief afvoer, herstel en eindschoonmaak, met een vaste prijs vooraf. Zie %s.</p>"
             % (dester("/", kind="brand"), dester("/", kind="bare"))),
        ],
        [links_rail("Andere situaties", [ONTRUIM_LINKS[1], ONTRUIM_LINKS[4], ONTRUIM_LINKS[6]]),
         hulpbox("/bezemschoon-opleveren/", "bezemschoon opleveren"),
         links_rail("Kennisbank", [("/kennisbank/verklaring-van-erfrecht/", "Verklaring van erfrecht"),
                                   ("/kennisbank/waardevolle-spullen/", "Waardevolle spullen herkennen")])],
    ))

    # ------------------------------------------------------------ inboedel opkoop
    out.append(_p(
        "/ontruimen/inboedel-opkoop/",
        "Inboedel verkopen: opkoop, taxatie en verrekening | SpoedWoningOntruiming.nl",
        "Inboedel verkopen",
        "Wanneer een inboedel geld waard is, hoe opkoop en taxatie werken, en waarom de opbrengst zelden de hele ontruiming dekt.",
        "Bijna elke inboedel bevat iets van waarde, maar zelden genoeg om de ontruiming te betalen. Dit is hoe opkopers rekenen, en welke voorwerpen het verschil maken.",
        [
            ("h2", "Wat een inboedel werkelijk opbrengt"),
            ("p", "De handelswaarde van gewone gebruikte meubels is in Nederland vrijwel nul. Een eiken eethoek uit de jaren negentig, een driezitsbank en een boekenkast leveren bij verkoop minder op dan het kost om ze op te halen, te reinigen, op te slaan en te verkopen. Kringloopwinkels nemen ze aan omdat hun bedrijfsmodel op vrijwilligers en subsidie draait, niet omdat de spullen waarde hebben."),
            ("p", "De waarde zit in een beperkte groep voorwerpen: goud en zilver, sieraden, horloges, klokken, munten en postzegels, design en merkmeubilair, gereedschap en machines, muziekinstrumenten, complete verzamelingen, en soms schilderijen en boeken. Wie die groep eruit haalt, heeft de opbrengst van de hele inboedel te pakken."),
            ("h2", "Hoe een opkoper rekent"),
            ("steps", [
                ("Taxatie ter plaatse",
                 "Een opkoper loopt de woning door en waardeert per categorie. Edelmetaal gaat op gewicht en dagkoers, de rest op geschatte doorverkoopwaarde."),
                ("Aftrek van doorverkoopmarge",
                 "Een handelaar biedt doorgaans tussen een kwart en de helft van wat hij verwacht te ontvangen. Dat verschil dekt zijn risico, opslag en verkooptijd."),
                ("Aftrek van afvoerkosten",
                 "Wat geen waarde heeft moet alsnog weg. Die kosten worden verrekend met het bod, en bij een gemiddelde woning is dat het grootste bedrag van de twee."),
                ("Netto bod of verrekening",
                 "Het resultaat is een bedrag dat wordt uitbetaald, of een korting op de ontruimingsrekening. Bij een gemiddelde woning eindigt dat vaker op een lagere rekening dan op een uitbetaling."),
            ]),
            ("h2", "Eerst zelf kijken loont"),
            ("p", "Vier categorieën zijn zonder kennis te herkennen en verdienen aparte aandacht voordat iemand anders in de woning komt."),
            ("table", ["Categorie", "Waar op te letten"], [
                ["Edelmetaal", "Stempels als 585, 750, 833, 925 of 14K. Ook in tandwerk, brillen en bestek."],
                ["Horloges en klokken", "Merknaam op wijzerplaat en kast. Mechanische uurwerken, ook kapot, houden waarde."],
                ["Munten en papiergeld", "Zilveren guldens van voor 1967 en buitenlandse verzamelingen in mappen."],
                ["Design", "Namen als Cassina, Artifort, Gispen, Pastoe, Thonet of Vitra op een label onder de zitting."],
            ]),
            ("note", "Papier eerst",
             "<p>Contant geld en waardepapieren zitten in nalatenschappen opvallend vaak tussen boeken, in enveloppen achter in een kast of onder een lade. Administratie doorlopen voordat er iets wordt afgevoerd, is de goedkoopste stap van het hele traject.</p>"),
            ("h2", "Alternatieven voor opkoop"),
            ("ul", [
                "Veilinghuis: voor stukken vanaf enkele honderden euro's. Kost commissie en tijd, maar levert bij bijzondere stukken meer op dan een opkoper.",
                "Online verkoop via Marktplaats of vergelijkbare kanalen: hoogste opbrengst per stuk, maar vraagt weken en de woning moet zolang beschikbaar blijven.",
                "Kringloop: geen opbrengst, wel gratis afvoer van bruikbare goederen en een tweede leven voor de spullen.",
                "Familie en kennissen: kosteloos, maar bij een nalatenschap eerst de verdeling schriftelijk vastleggen.",
            ]),
            ("warn", "Bij een nalatenschap: pas op met verkopen",
             "<p>Het verkopen van inboedelgoederen uit een nalatenschap geldt als een beschikkingshandeling en kan leiden tot zuivere aanvaarding, met persoonlijke aansprakelijkheid voor schulden. Wie nog niet weet of de nalatenschap positief is, verkoopt niets. Zie de pagina over <a href=\"/kennisbank/erfenis-aanvaarden/\">erfenis aanvaarden of verwerpen</a>.</p>"),
            ("h2", "Veelgestelde vragen"),
            ("faq", [
                ("Kost een taxatie geld?",
                 "<p>Bij een opkoper die ook de ontruiming doet, meestal niet. Een onafhankelijke taxateur rekent wel een tarief, wat alleen loont bij een vermoeden van bijzondere stukken.</p>"),
                ("Wordt de hele inboedel opgekocht of alleen het waardevolle?",
                 "<p>Meestal het geheel, waarbij de waarde van het bruikbare wordt verrekend met de afvoerkosten van de rest.</p>"),
                ("Kan een inboedel de ontruiming volledig dekken?",
                 "<p>Dat komt voor bij woningen met veel edelmetaal, design of complete verzamelingen. Bij een gemiddelde inboedel leidt het tot een korting, niet tot een nulrekening.</p>"),
                ("Hoe blijft de verdeling eerlijk tussen erfgenamen?",
                 "<p>Vooraf per kavel fotograferen en waarderen, dan verdelen of loten. Verkoop pas na overeenstemming van alle erfgenamen.</p>"),
            ]),
            ("partner", "Inboedel laten opkopen",
             "<p>%s koopt inboedels op en verrekent de waarde met de ontruimingskosten. De dienstpagina staat op %s.</p>"
             % (dester("/", kind="brand"), dester("/inboedel-opkoop/", kind="bare"))),
        ],
        [links_rail("Verder", [("/ontruimen/ontruimen-in-ruil-voor-inboedel/", "Ontruimen in ruil voor de inboedel"),
                               ("/kennisbank/waardevolle-spullen/", "Waardevolle spullen herkennen"),
                               ("/kennisbank/hergebruik-en-kringloop/", "Hergebruik en kringloop")]),
         hulpbox("/inboedel-opkoop/", "inboedel opkoop"),
         contactbox()],
    ))

    # ------------------------------------------------------------ in ruil voor
    out.append(_p(
        "/ontruimen/ontruimen-in-ruil-voor-inboedel/",
        "Ontruimen in ruil voor de inboedel: wanneer dat werkt | SpoedWoningOntruiming.nl",
        "Ontruimen in ruil voor de inboedel",
        "De constructie waarbij de inboedel de ontruiming betaalt: de voorwaarden, de rekensom en de valkuilen bij aanbiedingen die gratis heten.",
        "Ontruimen in ruil voor de inboedel betekent dat het bedrijf de spullen meeneemt en daar de kosten mee verrekent. Bij een klein deel van de woningen komt dat op nul uit. Bij de rest blijft er een rekening over, en dat hoort ook zo.",
        [
            ("h2", "De rekensom"),
            ("p", "Er staan twee bedragen tegenover elkaar. Aan de ene kant de opbrengst van de bruikbare inboedel na aftrek van de handelsmarge. Aan de andere kant de kosten van de ontruiming: manuren, transport, verwerkingstarieven, schoonmaak en eventueel herstel. Alleen wanneer het eerste bedrag het tweede benadert, is de constructie zinnig."),
            ("p", "In de praktijk gebeurt dat bij woningen met veel edelmetaal, sieraden, klokken, design of complete verzamelingen. Bij een gemiddelde woning met gewone meubels, kleding en huisraad is de opbrengst een fractie van de kosten. Een bedrijf dat dan toch gratis ontruimen belooft, verdient het elders terug of doet de klus half."),
            ("h2", "Wanneer het wel opgaat"),
            ("check", [
                "De woning bevat aantoonbaar waardevolle categorieën: goud, zilver, merkhorloges, antiek, design of een verzameling.",
                "De inboedel is compleet en niet al door familie uitgezocht.",
                "Er is geen zware afvoerlast: geen vloerbedekking eruit, geen vervuiling, geen zolder vol bouwafval.",
                "De woning is bereikbaar: begane grond of lift, en parkeren voor de deur.",
                "Er is geen harde deadline, want spoed haalt de marge eruit.",
            ]),
            ("h2", "Waar aanbiedingen misgaan"),
            ("ul", [
                "Krenten uit de pap: het waardevolle gaat mee, de rest blijft staan. Leg vast dat de woning volledig leeg wordt opgeleverd.",
                "Geen schriftelijke afspraak over de staat van oplevering, waardoor bezemschoon achteraf een aparte rekening blijkt.",
                "Nabetaling voor onvoorziene posten. Een vaste prijsafspraak vooraf, ook wanneer die nul is, hoort schriftelijk te zijn.",
                "Bij een nalatenschap: het weggeven van de inboedel in ruil voor werk is een beschikkingshandeling en kan zuivere aanvaarding opleveren.",
                "Geen bewijs van afvoer. Vraag om een afgiftebewijs of om foto's van de lege woning.",
            ]),
            ("warn", "Gratis bestaat, maar zelden",
             "<p>De reclame-uiting dat een ontruiming kosteloos is omdat het bedrijf de inboedel krijgt, gaat op voor een minderheid van de woningen. Een eerlijke aanbieder zegt na de opname of het uitkomt of niet, en noemt anders gewoon een bedrag.</p>"),
            ("h2", "Hoe de afspraak eruit hoort te zien"),
            ("table", ["Onderdeel", "Vast te leggen"], [
                ["Omvang", "Alle ruimtes benoemd: woning, zolder, kelder, berging, garage, tuin, balkon"],
                ["Eindresultaat", "Leeg en bezemschoon, of leeg plus eindschoonmaak"],
                ["Verrekening", "Welk bedrag de inboedel vertegenwoordigt en welk bedrag de ontruiming kost"],
                ["Uitzonderingen", "Wat niet meegaat: documenten, sieraden, fotoalbums, persoonlijke zaken"],
                ["Datum", "Uitvoeringsdatum en de datum waarop de sleutel ingeleverd moet zijn"],
                ["Bewijs", "Foto's na afloop en, bij een corporatie, het ondertekende opleverformulier"],
            ]),
            ("h2", "Veelgestelde vragen"),
            ("faq", [
                ("Is ontruimen in ruil voor de inboedel hetzelfde als inboedel opkoop?",
                 "<p>Bijna. Bij opkoop wordt een bedrag betaald of verrekend, bij deze constructie dekt de inboedel de rekening geheel of gedeeltelijk. Het is dezelfde rekensom, andere uitkomst.</p>"),
                ("Wat gebeurt er met spullen die niets opbrengen?",
                 "<p>Die worden gescheiden afgevoerd. Dat is precies de kostenpost die de constructie duur maakt.</p>"),
                ("Mag dit bij een nalatenschap?",
                 "<p>Alleen wanneer de erfgenamen zuiver hebben aanvaard, of wanneer vaststaat dat de nalatenschap positief is. Anders is er een risico op persoonlijke aansprakelijkheid voor schulden.</p>"),
                ("Hoe blijkt of het in een concrete situatie opgaat?",
                 "<p>Uit een opname op locatie. Een oordeel op basis van foto's alleen is bij deze constructie onbetrouwbaar.</p>"),
            ]),
            ("partner", "Ontruimen in ruil voor de inboedel",
             "<p>%s beoordeelt op locatie of de inboedel de kosten dekt en legt de uitkomst vooraf vast. De dienstpagina staat op %s.</p>"
             % (dester("/", kind="brand"), dester("/huis-ontruimen-in-ruil-voor-inboedel/", kind="bare"))),
        ],
        [links_rail("Verder", [("/ontruimen/inboedel-opkoop/", "Inboedel verkopen"),
                               ("/kosten/", "Wat kost een ontruiming"),
                               ("/kennisbank/waardevolle-spullen/", "Waardevolle spullen herkennen")]),
         hulpbox("/huis-ontruimen-in-ruil-voor-inboedel/", "ontruimen in ruil voor de inboedel"),
         contactbox()],
    ))

    # ------------------------------------------------------------ bedrijfspand
    out.append(_p(
        "/ontruimen/bedrijfspand/",
        "Bedrijfspand of winkel ontruimen: casco opleveren en archief | SpoedWoningOntruiming.nl",
        "Bedrijfspand en winkel ontruimen",
        "Kantoor, magazijn of winkel leegruimen: het huurcontract, casco opleveren, archiefvernietiging en de afvoer van apparatuur.",
        "Een zakelijke ontruiming lijkt op een woningontruiming, maar drie dingen verschillen: het huurcontract eist vaak veel meer, er zit data in het pand en er gelden regels voor de afvoer van apparatuur en bedrijfsafval.",
        [
            ("h2", "Het huurcontract bepaalt de klus"),
            ("p", "Bedrijfsruimte valt onder een ander regime dan woonruimte. In vrijwel alle zakelijke huurcontracten, meestal op basis van het ROZ-model, staat dat het pand in de oorspronkelijke staat wordt opgeleverd. Dat betekent: alle door de huurder aangebrachte zaken eruit, en het pand terug naar casco of naar de staat volgens het opleveringsrapport."),
            ("p", "In de praktijk gaat het om systeemplafonds, scheidingswanden, dataverkabeling, pantry's, vloerbedekking, verlichtingsarmaturen, luchtbehandeling en bij winkels om de complete winkelinrichting. Dat is bouwwerk en geen verhuizing, en het verklaart waarom een zakelijke ontruiming per vierkante meter duurder uitvalt dan een woning."),
            ("note", "Zoek het opleveringsrapport uit de begintijd",
             "<p>Bij zakelijke huur is dit document vrijwel altijd opgemaakt, inclusief foto's. Het bepaalt precies wat terug moet en wat mag blijven. Zonder dat rapport wordt de discussie met de verhuurder een schatting achteraf.</p>"),
            ("h2", "Data en archief"),
            ("p", "Papieren archief met persoonsgegevens mag niet bij het oud papier. De AVG verplicht tot een passende vernietiging, wat in de praktijk betekent: vernietiging volgens een erkende norm met een vernietigingscertificaat. Dat certificaat is het bewijsstuk bij een latere controle."),
            ("p", "Voor computers, servers, telefoons en kopieerapparaten geldt hetzelfde. In een kopieermachine zit een harde schijf met scans van alles wat er ooit doorheen is gegaan. Datadragers horen gewist of fysiek vernietigd te worden, met een verklaring erbij. Informatie over de regels staat op https://www.autoriteitpersoonsgegevens.nl."),
            ("h2", "Afvalstromen bij een bedrijfspand"),
            ("table", ["Stroom", "Regel"], [
                ["Elektrische apparatuur", "Valt onder de regeling voor afgedankte elektrische apparaten, gescheiden inleveren bij een erkende verwerker"],
                ["Tl-buizen en armaturen", "Kwikhoudend, aparte inzameling verplicht"],
                ["Koel- en vriesapparatuur", "Koudemiddel moet door een gecertificeerd bedrijf worden afgetapt"],
                ["Bouw- en sloopafval", "Gescheiden aanbieden, meestal per container en per ton afgerekend"],
                ["Gevaarlijke stoffen", "Verf, oplosmiddelen, accu's en gasflessen via een erkende inzamelaar met begeleidingsbrief"],
                ["Bedrijfsafval algemeen", "Niet via de gemeentelijke milieustraat, die is voor particulieren"],
            ]),
            ("h2", "Winkelpanden"),
            ("p", "Een winkel bevat vaste inrichting die zelden zonder schade te verwijderen is: wandpanelen, schappen, kassabalie, koeling, verlaagde plafonds, ledrails en soms een sprinklerinstallatie. Bij een franchiseformule zit er bovendien een merkgebonden inrichting in die volgens de formuleovereenkomst terug moet naar de franchisegever of vernietigd moet worden."),
            ("p", "Restvoorraad is een aparte vraag. Doorverkoop aan een partijhandel levert een fractie van de inkoopwaarde op, maar scheelt afvoerkosten en vult de laatste dagen van een liquidatie."),
            ("h2", "Planning"),
            ("steps", [
                ("Contract en opleveringsrapport naast elkaar",
                 "Bepaal wat er precies terug moet. Vraag de verhuurder om een schriftelijke bevestiging van de eisen."),
                ("Data en archief eerst",
                 "Vernietiging plannen voor de ontruiming, want daarna is niet meer te achterhalen wat waar stond."),
                ("Herbruikbaar apart zetten",
                 "Kantoormeubilair, vergaderstoelen en recente apparatuur hebben restwaarde die de rekening drukt."),
                ("Ontruimen en demonteren",
                 "Eerst los meubilair, dan inrichting, dan bouwkundige zaken. Dat scheelt manuren en containerritten."),
                ("Herstel en oplevering",
                 "Wanden dichten, vloeren egaliseren, plafonds herstellen, schoonmaak en oplevering met de verhuurder erbij."),
            ]),
            ("h2", "Veelgestelde vragen"),
            ("faq", [
                ("Moet een bedrijfspand casco worden opgeleverd?",
                 "<p>Meestal wel. Het ROZ-model gaat uit van oplevering in de staat bij aanvang. Afwijkende afspraken staan in de allonge of in de opleveringsstaat.</p>"),
                ("Kan een ontruiming buiten kantooruren?",
                 "<p>Ja, en bij winkelcentra en kantoorverzamelgebouwen is dat vaak verplicht vanwege de huisregels en de beschikbaarheid van de lift.</p>"),
                ("Hoe zit het met huurdersinvesteringen die zijn afgeschreven?",
                 "<p>Afschrijving in de boekhouding zegt niets over de opleververplichting. Bepalend is wat in het contract en het opleveringsrapport staat.</p>"),
                ("Wie regelt de archiefvernietiging?",
                 "<p>Ontruimingsbedrijven werken hiervoor samen met een gecertificeerde vernietiger. Vraag altijd om het vernietigingscertificaat.</p>"),
            ]),
            ("partner", "Zakelijke ontruiming",
             "<p>%s ontruimt kantoren, magazijnen en winkels inclusief demontage en herstel. De pagina over bedrijfspanden staat op %s, die over winkels op %s.</p>"
             % (dester("/", kind="brand"), dester("/bedrijfspand-ontruimen/", kind="bare"),
                dester("/winkel-ontruimen/", kind="bare"))),
        ],
        [links_rail("Andere situaties", [ONTRUIM_LINKS[0], ONTRUIM_LINKS[4], ONTRUIM_LINKS[3]]),
         hulpbox("/bedrijfspand-ontruimen/", "bedrijfspand ontruimen"),
         links_rail("Kennisbank", [("/kennisbank/grofvuil-en-milieustraat/", "Grofvuil en milieustraat"),
                                   ("/kennisbank/asbest-in-de-woning/", "Asbest in de woning")])],
    ))

    return out
